= YUBIHSM-SHELL(1)
:doctype:	manpage
:man source:	yubihsm-shell
:man version:	2.0.0

== NAME
yubihsm-shell - yubihsm-shell

== SYNOPSIS
*yubihsm-shell* [OPTIONS]...

== OPTIONS
*-h, --help*::
Print help and exit

*-V, --version*::
Print version and exit

*-a, --action=ENUM*::
Action to perform  (possible
values="decrypt-pkcs1v15", "decrypt-oaep",
"derive-ecdh", "decrypt-aesccm",
"encrypt-aesccm", "generate-asymmetric-key",
"generate-hmac-key", "generate-wrap-key",
"generate-otp-aead-key", "get-logs",
"get-opaque", "get-pseudo-random",
"get-storage-info", "get-public-key",
"get-object-info", "get-wrapped",
"get-device-info", "get-template",
"list-objects", "put-asymmetric-key",
"put-authentication-key", "put-opaque",
"put-option", "put-hmac-key",
"put-wrap-key", "put-wrapped",
"put-template", "put-otp-aead-key",
"sign-ecdsa", "sign-pkcs1v15", "sign-pss",
"sign-eddsa", "sign-hmac", "reset",
"delete-object", "sign-ssh-certificate",
"benchmark", "create-otp-aead",
"randomize-otp-aead", "decrypt-otp",
"sign-attestation-certificate")

*-p, --password=STRING*::
Authentication password

*--authkey=INT*::
Authentication key  (default=`1')

*-i, --object-id=SHORT*::
Object ID  (default=`0')

*-l, --label=STRING*::
Object label  (default=`')

*-d, --domains=STRING*::
Object domains
(default=`1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16')

*-c, --capabilities=STRING*::
Capabilities for an object  (default=`0')

*-t, --object-type=STRING*::
Object type

*--delegated=STRING*::
Delegated capabilities  (default=`0')

*--new-password=STRING*::
New authentication password

*-A, --algorithm=STRING*::
Operation algorithm

*--nonce=INT*::
OTP nonce

*--count=INT*::
Number of bytes to request  (default=`256')

*--wrap-id=INT*::
Wrap key ID

*--template-id=INT*::
Template ID

*--attestation-id=INT*::
Attestation ID

*--in=STRING*::
Input data (filename)  (default=`-')

*--out=STRING*::
Output data (filename)  (default=`-')

*--informat=ENUM*::
Input format  (possible values="default",
"base64", "binary", "PEM", "password",
"hex", "ASCII" default=`default')

*--outformat=ENUM*::
Input and output format  (possible
values="default", "base64", "binary",
"PEM", "hex", "ASCII" default=`default')

*-f, --config-file=STRING*::
Configuration file to read  (default=`')

*-C, --connector=STRING*::
List of connectors to use

*--cacert=STRING*::
HTTPS cacert for connector

*--proxy=STRING*::
Proxy server to use for connector

*-v, --verbose=INT*::
Print more information  (default=`0')

