== Key Storage Provider

The Key Storage Provider (KSP) for Windows CNG works for RSA2048,
RSA4096, but has been tested to work well with ADCS as follows:

The following installs the KSP, the Connector Service, and uses it for ADCS
with the default Authkey (`1`) and password.

During the `Install-AdcsCertificationAuthority` command, you should see the
YubiHSM 2 light flash rapidly as ADCS uses the KSP to generate an RSA 2048 bit
key in hardware.
`Restart-Computer` may be needed for ADCS to work properly.

  PS1> msiexec /i "yubihsm-connector-windows-amd64.msi" /passive ACCEPT=yes
  PS1> msiexec /i "yubihsm-cngprovider-windows-amd64.msi" /passive  ACCEPT=yes
  PS1> Install-WindowsFeature AD-Certificate -Verbose
  PS1> Install-AdcsCertificationAuthority -CAType EnterpriseRootCa    \
      -CryptoProviderName "RSA#YubiHSM Key Storage Provider"          \
      -KeyLength 2048 -HashAlgorithmName SHA256 -ValidityPeriod Years \
      -ValidityPeriodUnits 5
  PS1> Install-AdcsOnlineResponder

If you are using a different Authkey, password, or Connector for the KSP,
you can specify them as follows (defaults are shown):

  PS1> Set-ItemProperty -path HKLM:\SOFTWARE\Yubico\YubiHSM \
      -name ConnectorURL -Type String -Value http://127.0.0.1:12345
  PS1> Set-ItemProperty -path HKLM:\SOFTWARE\Yubico\YubiHSM \
      -name AuthKeysetPassword -Type String -Value adcspassword
  PS1> Set-ItemProperty -path HKLM:\SOFTWARE\Yubico\YubiHSM \
      -name AuthKeysetID -Type DWord -Value 10

Default configuration for the connector is:
link:../yubihsm-connector[`programdata\yubiHSM\yubihsm-connector.yaml`] - need Administrator rights to access the file.

=== Additional Documentation for YubiHSM Key Storage Provider

- For instructions on how to move a software-based key into the YubiHSM 2 for use with the Key Storage Provider, please see link:Software_keys_to_ksp.adoc[Move Software Keys to Key Storage Provider].
- More information about link:Status_codes.adoc[YubiHSM 2 status codes] in Windows.
