== Prerequisites and Preparations

The audience of this document is expected to be an experienced systems administrator with a good understanding of Windows Server management. In addition, it helps to be familiar with the terminology, software and tools specific to YubiHSM 2. As a primer for these, refer to the link:Terminology_Used.adoc[Terminology chapter].

In order to follow the steps provided in this guide, be sure you meet the following prerequisites, having:

* Access to Microsoft Windows Server 2012, R2/2016, 2019 with Active Directory in an offline, air-gapped environment, such as a secure computer network that is physically isolated from unsecured networks such as the internet. You must also have elevated system privileges.

* YubiHSM 2 software and tools for Windows downloaded from link:../Releases/[the YubiHSM 2 Release page]/ and available on the system to be used.

* Two (2) factory-reset YubiHSM 2 devices, one for deployment and one for backup in hardware.

* Key custodians identified as per local requirements and available to participate. For more information about key custodians and the associated ‘M of N’ key shares, see link:../Usage_Guides/YubiHSM_2_Windows_Deployment_Guide--Configure_YubiHSM_2_Key_Storage_Provider_for_Microsoft_Windows_Server/Back_Up_and_Restore_Key_Material.adoc["Key Splitting and Key Custodians" in the YubiHSM 2 Windows Deployment Guide].


link:Installing_the_YubiHSM_2_Tools_and_Software.adoc[Next: Installing the YubiHSM 2 Tools and Software]
