= Passkey client application prerequisites
:description: Prerequisites to begin implementing a passkey client application
:keywords: passkey, passkeys, developer, high assurance, FIDO2, CTAP, WebAuthn, client application

Prerequisites to begin implementing a passkey client application

Prior to implementing a passkey client application, there are some prerequisites that should be created to help assist you in developing your application. This guide will present these prerequisites prior to diving into the registration and authentication implementation guidance.

== Passkey relying party
You will need a relying party (backend application) that supports passkey operations. The relying party will need to be able to provide your client applications with the necessary inputs to begin registration and authentication ceremonies. The backend application will also need to support credential management, and storage operations. 

If you do not have a relying party, please follow our guidance in the link below to begin developing your backend application.

link:/Passkeys/Passkey_relying_party_implementation_guidance/[Passkey for developers relying party implementation guidance]

When you have all your prerequisites in place, click the link below to continue to implementation guidance for registration flows.

link:/Passkeys/Passkey_client_application_implementation_guidance/Passkey_registration_implementation_guidance.html[Continue to passkey client application registration implementation guidance]
