#!/usr/bin/env python

import json
from os import path
from devyco.main import main

if __name__ == '__main__':
    base_dir = path.abspath(path.dirname(__file__))  # Use dir of file
    settings = {}
    settings_file = path.join(base_dir, 'settings.json')
    if path.isfile(settings_file):
        with open(settings_file, 'r') as f:
            settings = json.load(f)

    main(base_dir, settings)
    print "All done!"
