= FIDO2 SSH Authentication

Starting with version 8.2p1, OpenSSH has added support for registering and authenticating using FIDO2 Credentials. With support for both _discoverable_ and _non-discoverable_ credentials, OpenSSH thus allows using both Security Keys and YubiKeys. OpenSSH with support for FIDO2 credentials is available on Linux and MacOS, but not yet on Windows.

Using FIDO2 credentials requires configuring OpenSSH on both the client and the server. Slightly different settings are required depending on whether discoverable or non-discoverable credentials are used.


== Discoverable vs Non-Discoverable Credentials
Before configuring an OpenSSH server or client to use FIDO2 credentials, one must first decide whether to use discoverable or non-discoverable credentials. Each option has different strengths, and the best option depends on the environment that SSH is being used in. Non-discoverable credentials require that the private key is stored in the folder ~/.ssh as well as the presence of the YubiKey. For this reason, it is not recommended to use non-discoverable credentials with a publicly accessible endpoint.

.*Benefits of non-discoverable keys:*
* They cannot be used by another person in case the YubiKey is lost.
* Ideal for systems that require higher levels of security.

.*Benefits of discoverable keys:*
* They can be moved to any compatible workstation and used to authenticate with touch and a FIDO2 PIN.
* Ideal for ease of access where the PIN is known.

== Setting up OpenSSH for FIDO2 Authentication
Regardless of which type of credential is used, some prerequisites must be met:

* Both the local and remote systems must be running OpenSSH version 8.2p1 or higher in order to use non-discoverable credentials.
* Both the local and remote systems must be running OpenSSH version 8.3 or higher in order to use discoverable credentials.
* A FIDO2 PIN must be set on the YubiKey. This can be done using YubiKey Manager, for instance.

=== Instructions for Discoverable Credentials
. Insert a YubiKey into the computer.
. Open a Terminal window and type the following command to generate a key using the `ecdsa` curve:
+
--
`ssh-keygen -t ecdsa-sk -O resident -O application=ssh:YourTextHere`

To use the `ed25519` curve, use the following command instead:

`ssh-keygen -t ed25519-sk -O resident -O application=ssh:YourTextHere`

_For both commands, replace_ `YourTextHere` _with anything that helps you identify where this key is being used, for example a server name. This option is not mandatory and may be omitted._
--
. SSH will ask the user to enter their PIN and touch the device. At the same time, the YubiKey will flash. _Note that some systems do not ask the user to touch the YubiKey, requiring only the PIN._

. SSH will save two files with default names `id_ecdsa_sk` and `id_ecdsa_sk.pub`. The user can always choose different filenames when prompted for a save location. The first file, `id_ecdsa_sk`, contains information about the private key credential stored on the YubiKey. The second file, `id_ecdsa_sk.pub`, is the public key required for authentication to a remote system.  

. The following command adds the public key to a remote server:
+
--
`ssh-copy-id -i ~/.ssh/id_ecdsa_sk user@host`
--

==== Using an existing discoverable credential on a new computer
. After following the previous instructions, insert the configured YubiKey into the new computer.

. Open a Terminal window and type the following commands:
+
--
`cd ~/.ssh`

`ssh-keygen -K`
--

. SSH will ask the user to enter their PIN and touch the device. At the same time, the YubiKey will flash. However, some systems may not ask for a touch.

. If this is the only credential on the system, you may rename the exported credentials as `id_ecdsa_sk` and `id_ecdsa_sk.pub` to allow seamless authentication.  
+
--
When multiple credentials exist in the directory ~/.ssh, the proper command to authenticate to a remote system is:
`ssh -i ~/.ssh/id_ecdsa_sk user@host` (replace `id_ecdsa_sk` with the correct identity file corresponding to the remote server).

SSH can be made to use specific credentials with the help of the config file. The SSH config file `~/.ssh/config` may not exist and so may need to be created. For example, adding the following two lines to `~/.ssh/config` will tell SSH to always use the key `id_ecdsa_sk_rk_credential_example_com` when accessing example.demo.com.

----
Host example.demo.com 
IdentityFile ~/.ssh/id_ecdsa_sk_rk_credential_example_com
----

--

. To ensure that the migration was successful, SSH into the remote system from the new computer and touch the key when prompted.

=== Instructions for Non-Discoverable Credentials
. Insert a YubiKey into the computer.

. Open a Terminal window and type the following command to generate a key using the `ecdsa` curve:
+
--
`ssh-keygen -t ecdsa-sk`

To use the `ed25519` curve, use the following command instead:
`ssh-keygen -t ed25519-sk`
--

. SSH will ask the user to enter their PIN and touch the device. At the same time, the YubiKey will flash. _Note that some systems do not ask the user to touch the YubiKey, requiring only the PIN._

. As was the case with discoverable credentials above, SSH will save two files with default names `id_ecdsa_sk` (the private key) and `id_ecdsa_sk.pub` (the public key). With non-discoverable credentials, however, nothing is actually stored on the YubiKey itself.

. The following command adds the public key to a remote server:
+
--
`ssh-copy-id -i ~/.ssh/id_ecdsa_sk user@host`
--

==== Using an existing non-discoverable credential on a new computer
. After following the previous instructions, insert the configured YubiKey into the new computer.

. Copy the two files `id_ecdsa_sk` and `id_ecdsa_sk.pub` from step 4 in the previous instructions to the folder ~/.ssh on the new computer.

. To ensure that the migration was successful, SSH into the remote system from the new computer and touch the key when prompted.


== Troubleshooting
If you are prompted for a password instead of the YubiKey, the remote system may need reconfiguring. Here are a few things to try out or check:

* Restart the system or log out and back in again.
* Check the OpenSSH version with the command `ssh -V`. The OpenSSH version must be at least 8.2p1 to use non-discoverable keys and at least 8.3 to use discoverable keys.
* If the remote system is Linux-based, then check the logs:
** Ubuntu/Debian: `tail /var/log/syslog | grep sshd`
** Fedora: `journalctl -r /usr/sbin/sshd`
* Run debug mode from the local computer with `ssh -vvvv username@host.com` and review the output for any errors.
* Sometimes, when logging on to the remote system, an error will be displayed saying that `/home/username/.ssh/id_ecdsa_sk` cannot be read. This may happen because SSH cannot see the YubiKey properly, so just unplug and reinsert the YubiKey.
* SSH public keys will be rejected when the private key has incorrect file permissions. Correct this situation by issuing the command `chmod 600 ~/.ssh/id_ecdsa_sk` (assuming the private key is located at `~/.ssh/id_ecdsa_sk`).
* The YubiKey may not flash or prompt for touch due to inconsistencies between different operating systems.
