== Advanced Topics

=== Attestation Certificates
Upon registration, a device gives the server its _attestation certificate_.
You can (optionally) use the attestation certificate to assert certain device types or vendors.

For example, you can verify that a device is produced by Yubico by verifying that the
attestation certificate is signed by
link:https://developers.yubico.com/u2f/yubico-u2f-ca-certs.txt[Yubico's CA].
 

=== Challenge Expiration
It is good practice to treat challenges older than _X_ minutes as expired.


=== Device counters
U2F devices sends an incrementing counter to the server upon authentication.
The U2F library uses this counter to prevent the use of cloned devices.

For protection to work, you have to persist the device info after each authentication.
However, all U2F compatible devices by Yubico uses tamper-resistant Secure Elements designed
to not being cloneable.


=== Multiple devices per user
To support multiple devices per user, generate

[source, python]
----
# handles HTTP requests to /start_authentication
def start_authentication(username, password):
  verify_user_pass(username, password)
  registered_devices = device_store.get(username)
  challenges = [u2f.start_authentication(device, APP_ID) for device in registered_devices]
  challenge_store.set(username, challenge)
  return toJsonList(challenges)
----

This could for example result in the following JSON:

[source, javascript]
----
[
  {
    "version": "U2F_V2",
    "challenge": "b7ma_N3pzL7zVCQCTpuUr55t8HQqXEDEdPapNzx6_IE",
    "keyHandle": "UuYvIIg9fpAC6AkbWT9Pe0T3iIkRsYcz7N5p3EeGleC4k8e8P75BVHnlm0cpXIHL8Pq7ERhslI9GX4oj0uB"
  },
  {
    "version": "U2F_V2",
    "challenge": "JCxNJtapiNnia0P9RaWTAVO1gObWifWV5vPVKIjw6lo",
    "keyHandle": "EUryGFjTgMnSqiuEGbxiaBRaVGmilz62gKsBz56HV9o90tDBBvdPfV3vrIV_1oKhu8DSIPHol3rarGymRcA"
  },
  {
    "version": "U2F_V2",
    "challenge": "FhG8tCCizpX5uGPMXUdkw8O3giwA8id0rbQA4FJS6kE",
    "keyHandle": "tveAECT7LBjvHQ1BxUuUB13EVFLR0iPoQtSFZM7DmiGVObvHD85IYTH5G8ekqQrgpZaJhUnGKyVaegIopJT"
  }
]
----

