== Advanced Topics

=== Attestation Certificates
Upon registration, a device gives the server its _attestation certificate_.
You can (optionally) use the attestation certificate to assert certain device types or vendors.

For example, you can verify that a device is produced by Yubico by verifying that the
attestation certificate is signed by
link:https://developers.yubico.com/u2f/yubico-u2f-ca-certs.txt[Yubico's CA]. In Python,
it would look like this:

[source, python]
----
attestation_cert.verify(yubico_ca_cert.get_pubkey())
----

=== Challenge Expiration
It is good practice to treat challenges older than _X_ minutes as expired.

=== Device counters
U2F devices sends an incrementing counter to the server upon authentication.
The U2F library uses this counter to prevent the use of cloned devices.
For this protection to work, you have to persist the device info after each authentication.
However, all U2F compatible devices by Yubico uses tamper-resistant Secure Elements designed
to be impossible to clone.

==== Handling counter errors
If a the counter ever decrements, the device has been cloned. The best way to handle
this depends on the application. You might want to alert the user or lock their account.

