== Advanced Topics

=== Attestation Certificates
Upon registration, a device gives the server its _attestation certificate_.
You can (optionally) use the attestation certificate to assert certain device types or vendors.

For example, you can verify that a device is produced by Yubico by verifying that the
attestation certificate is signed by
link:https://developers.yubico.com/u2f/yubico-u2f-ca-certs.txt[Yubico's CA]. In Python,
it would look like this:

[source, python]
----
attestation_cert.verify(yubico_ca_cert.get_pubkey())
----

=== Challenge Expiration
It is good practice to treat challenges older than _X_ minutes as expired.

=== Device counters
U2F devices sends an incrementing counter to the server upon authentication.
The U2F library uses this counter to prevent the use of cloned devices.
For this protection to work, you have to persist the device info after each authentication.
However, all U2F compatible devices by Yubico uses tamper-resistant Secure Elements designed
to be impossible to clone.

==== Handling counter errors ====
If a the counter ever decrements, the device has been cloned. The best way to handle
this depends on the application. You might want to alert the user or lock their account.


=== Multiple devices per user
Some U2F server libraries has a high-level API for multiple devices. If the library that
you are using does not, you want to do something like this when authenticating a user with
multiple devices registered:

[source, python]
----
# handles HTTP requests to /start_authentication
def start_authentication(username, password):
  verify_user_pass(username, password)
  registered_devices = device_store.get(username)
  challenges = [u2f.start_authentication(device, APP_ID) for device
                in registered_devices]
  challenge_store.set(username, challenge)
  return toJsonList(challenges)
----

This should result in a JSON list of authentication requests, for example:

[source, json]
----
[
  {
    "version": "U2F_V2",
    "challenge": "b7ma_N3pzL7zVCQCTpuUr55t8HQqXEDEdPapNzx6_IE",
    "keyHandle": "UuYvIIg9fpAC6AkbWT9Pe0T3iIkRsYczGleC4k8e8P75BVHnPq7ERhslI9GX4oj0uB"
  },
  {
    "version": "U2F_V2",
    "challenge": "JCxNJtapiNnia0P9RaWTAVO1gObWifWV5vPVKIjw6lo",
    "keyHandle": "EUryGFjTgMnSqiuEGbxiaBRaVGmilz62V9o90tDBBvdPfV3vrIIPHol3rarGymRcA"
  },
  {
    "version": "U2F_V2",
    "challenge": "FhG8tCCizpX5uGPMXUdkw8O3giwA8id0rbQA4FJS6kE",
    "keyHandle": "tveAECT7LBjvHQ1BxUuUB13EVFLR0iPomiGVObvHD85IYTH5G8eUnGKyVaegIopJT"
  }
]
----

