== Implementing U2F using a library ==
Let us have a look at the U2F sequence diagram:

++++
<div class="diagram">
participant Token
participant Browser
Browser->Server: username and\npassword
Note over Server: verify username\nand password
Note over Server: generate U2F\nchallenge
Server->Browser: challenge (e.g. embedded\nin a HTML page)
Browser->Token: challenge
Note over Token: user touches\nbutton
Token-->Browser: response
Browser-->Server: response
Note over Server: verify response
</div>
++++


=== Server-side ===

A server-side U2F library has 4 basic functions: _Start registration, Finish registration, Start authentication_ and _Finish authentication_.
Below is an example of how these functions can be used in a web server:

==== Registration ====

[source, python]
# handles HTTP requests to /start_registration
def start_registration(username, password):
  verify_user_pass(username, password)
  challenge = u2f_lib.start_registration() # generate challenge
  datastore.set('u2f_registration_challenge_' + username, challenge)
  return challenge

[source, python]
# handles HTTP requests to /finish_registration
def finish_registration(username, password, tokenResponse):
  challenge = datastore.get('u2f_registration_challenge_' + username)
  userdata = u2f_lib.finish_registration(challenge, tokenResponse) # verify response
  datastore.set('u2f_user_data_' + username, userdata)
  return "Success!"

==== Authentication ====

[source, python]
# handles HTTP requests to /start_authentication
def start_authentication(username, password):
  verify_user_pass(username, password)
  userdata = datastore.get('u2f_user_data_' + username)
  challenge = u2f_lib.start_authentication(userdata) # generate challenge
  datastore.set('u2f_authentication_challenge_' + username, challenge)
  return challenge

[source, python]
# handles HTTP requests to /finish_authentication
def finish_authentication(username, password, tokenResponse):
  challenge = datastore.get('u2f_authentication_challenge_' + username)
  u2f_lib.finish_authentication(challenge, tokenResponse) # verify response
  return "Success!"


=== Client-side  ===
As shown in the diagram above, the main part of the client (web browser) is to
be a middle-man between the server and the hardware token.

Below is an example snippet using JQuery. The `u2f` object is provided by browsers that supports U2F.

[source, javascript]
/* u2f-login.html */
var challenge = // From the server (e.g. this row could be dynamically generated by the server)
$("#u2f-modal-dialog").show(); // Prompt user to touch token button
u2f.sign([challenge], [], // Forward challenge to token
  function(tokenResponse) {
	$('#u2f-form-data').val(JSON.stringify(tokenResponse));
	$('#u2f-form').submit(); // Send token response back to server
  }
);

When registering a new token `u2f.register` is used instead of `u2f.sign`.


pass::[<script src="jquery-1.11.1.min.js"></script><script src="raphael-min.js"></script><script src="underscore-min.js"></script><script src="sequence-diagram-min.js"></script><script>$(".diagram").sequenceDiagram({theme: 'simple'});</script>]

