== Using a U2F library ==
Let us have a look at the U2F sequence diagram:

[mscgen]
----
msc {

   # Entities
   d [label = "Device"], b [label="Browser"], s [label="Server"];

   # Arcs
   |||;
   b -> s [label = "username and password"];
   s rbox s [label="verify password"];
   s rbox s [label="generate challenge", linecolor="#44B724", textcolor="#44B724"];
   s -> b [label = "challenge"];
   b rbox b [label = "u2f.sign(challenge)"];
   b => d [label = "challenge", linecolor="#2156a5", textcolor="#2156a5"];
   d rbox d [label="user touches button", linecolor="#2156a5", textcolor="#2156a5"];
   d >> b [label = "response", linecolor="#2156a5", textcolor="#2156a5"];
   b -> s [label = "response"];
   s rbox s [label="verify response", linecolor="#44B724", textcolor="#44B724"];
}
----

The blue part is handled by the U2F client (e.g. the web browser) and the green parts are handled by the U2F server library.


=== Server-side ===

A server-side U2F library has 4 basic functions: _Start registration, Finish registration, Start authentication_ and _Finish authentication_.
Below is an example of how these functions can be used in a web server:

==== Registration ====

[source, python]
----
# handles HTTP requests to /start_registration
def start_registration(username):
  challenge = u2f_lib.start_registration(APP_ID)
  challenge_store.set(username, challenge)
  return challenge
----


[source, python]
----
# handles HTTP requests to /finish_registration
def finish_registration(username, device_response):
  challenge = challenge_store.pop(username)
  registered_device = u2f_lib.finish_registration(challenge, device_response)
  device_store.set(username, registered_device)
  return "Success!"
----


==== Authentication ====

[source, python]
----
# handles HTTP requests to /start_authentication
def start_authentication(username, password):
  verify_user_pass(username, password)
  registered_devices = device_store.get(username)
  challenge = u2f_lib.start_authentication(registered_devices, APP_ID)
  challenge_store.set(username, challenge)
  return challenge
----

[source, python]
----
# handles HTTP requests to /finish_authentication
def finish_authentication(username, password, device_response):
  challenge = challenge_store.pop(username)
  u2f_lib.finish_authentication(challenge, device_response, registered_devices)
  return "Success!"
----

In the example above `challenge_store` is a link:http://en.wikipedia.org/wiki/Data_access_object[DAO] that stores
challenges temporarily. The other DAO, `device_store`, persists data permanently. For link:../App_ID.html[most cases],
`APP_ID` is the base URL of this web app, for example:

[source, python]
APP_ID = "https://login.example.com"

...or, when developing locally:

[source, python]
APP_ID = "https://localhost:8080"

=== Client-side  ===
This section assumes that you are building a web site. If this is not the case,
have a look at our link:/Software_Projects/FIDO_U2F/U2F_Host_Libraries/[U2F host libraries] instead.
Also not that Chrome is currently the only web browser supporting U2F.

The main part of the client is to
be a middle-man between the server and the U2F device.
For web browsers, a U2F JavaScript API is used to
communicate with the device (exposed via the `u2f` object).

.Example snippet
[source, html]
----
<!-- u2f-login.html -->
<script src="https://demo.yubico.com/js/u2f-api.js"></script>
<script>
var challenge = ... // (1)
u2f.sign([challenge], [],
  function(deviceResponse) {
    document.getElementById('response-input').value = JSON.stringify(deviceResponse)
    document.getElementById('login-form').submit() // (2)
  }
);
</script>
----
<1> From the server (e.g. this row could be dynamically generated by the server).
<2> Send device response back to server.

When registering a new device `u2f.register` is used instead of `u2f.sign`. The complete U2F JavaScript API can
be found link:/U2F/Protocol_details/Specification.html[here].

For a complete example, see
https://github.com/Yubico/java-u2flib-server/blob/master/u2flib-server-demo/src/main/resources/demo/view/authenticate.ftl[this demo server].

=== Complete example code
For complete example code (both server and client) in various languages, have a look at link:List_of_libraries.html[respective U2F library]'s accompanied demo server.

