== YubiCloud Validation Servers

[Note]
======
<<<<<<< HEAD
Yubico has declared end-of-life of YubiKey Validation Server (YK-VAL) and YubiKey Key Storage Module (YK-KSM). These have been moved to link://github.com/YubicoLabs/yubikey-ksm[YubicoLabs] as a reference architecture. See article, link:/support.yubico.com/hc/en-us/articles/360021227000[YK-VAL, YK-KSM and YubiHSM 1 End-of-Life].
=======
Yubico has declared end-of-life for the YubiKey Validation Server (YK-VAL) and YubiKey Key Storage Module (YK-KSM). These have been moved to link://github.com/YubicoLabs/yubikey-ksm[YubicoLabs] as a reference architecture. See article, link:https://support.yubico.com/hc/en-us/articles/360021227000[YK-VAL, YK-KSM and YubiHSM 1 End-of-Life].
>>>>>>> 456647ee9dcca05aafc4d68935558d154423db61
======

If you don't want to use YubiCloud, you can host one of these validation server(s) yourself.

PHP validation server:: link:/yubikey-val/[yubikey-val]
PHP key storage module:: link:/yubikey-ksm/[yubikey-ksm]

Third party implementations can be discovered on link:https://github.com/search?q=yubicloud+validation[GitHub] for example.
