== What is FIDO2 and Web Authentication?
FIDO2 and WebAuthn mark an evolution of the link:https://developers.yubico.com/U2F/[FIDO U2F] open authentication standard. They now enable strong passwordless authentication built on public key cryptography using hardware devices like security keys, mobile phones, and other built-in devices.

FIDO2 is an open authentication standard that consists of the link:https://www.w3.org/TR/webauthn/[W3C Web Authentication API] (WebAuthn), and the link:https://fidoalliance.org/specifications/download/[FIDO2 Client to Authentication Protocol] (CTAP). CTAP is an application layer protocol used for communication between a client (browser) or a platform (operating system) and an external authenticator (YubiKey 5). Yubico, Microsoft and Google are the core contributors to the W3C WebAuthn and FIDO2 CTAP2 specifications.

Like U2F, the FIDO2/WebAuthn standard offers the same high level of security, as it is based on public key cryptography and is intended to solve additional user scenarios including first factor (passwordless) and multi-factor authentication. With these new capabilities, the hardware security key can entirely replace weak static username/password credentials with strong hardware-backed public/private-key credentials.  These credentials can not be reused, replayed or shared across services, and are not subject to phishing and MiTM attacks or server breaches.

=== FIDO2/WebAuthn Advantages

[horizontal]
Strong security:: Replaces weak passwords with strong hardware-based authentication using public key crypto to protect against phishing, session hijacking, man-in-the-middle, and malware attacks.
Privacy Protection:: A FIDO2 authenticator generates a new pair of keys for every service, and the service stores only the public key. With this approach, no secrets are shared between service providers.
Multiple choices:: Open standards provide flexibility and product choice. Designed for existing phones and computers, for many authentication modalities, and with different communication methods (USB and NFC).
Cost-efficient:: Hardware authenticators are affordable and available for link:https://www.yubico.com/store/[purchase online]. Yubico offers free and open source server software for back-end integration.
Layered approach:: For organizations requiring a higher level of authentication security, WebAuthn supports use of a hardware authentication device with a PIN, biometric or gesture for additional protection.

=== How it works
The following diagrams show the basic FIDO2/WebAuthn user flows:

==== Registration sequence diagram
[mscgen]
----
msc {
  # Options
  hscale = "1.5";

  # Entities
  a [label="Authenticator"],
  c [label="Client/Platform"],
  s [label="Server"];

  # Arcs
  |||;
  s => c [label="1. publicKeyCredentialCreationOptions\n(challenge, userInfo, relyingPartyInfo)\n\n\n"];
  c => a [label="2. authenticatorMakeCredential\n(challenge, userInfo, relyingPartyInfo,\nclientDataHash)\n\n\n\n"];
  a rbox a [label="\n3. Create new Key Pair and Attestation\n"];
  |||;
  a => c [label="4. attestationObject\n(newPublicKey, credentialId, attestation)\n\n\n"];
  c => s [label="5. authenticatorAttestationResponse\n(credentialId, clientData, attestationObject)\n\n\n"];
  s rbox s [label="\n6. Sever validation\n"];
  |||;
}
----

==== Authentication sequence diagram
[mscgen]
----
msc {
  # Options
  hscale = "1.5";

  # Entities
  a [label="Authenticator"],
  c [label="Client/Platform"],
  s [label="Server"];

  # Arcs
  |||;
  s => c [label="1. publicKeyCredentialRequestOptions\n(challenge)\n\n\n"];
  c => a [label="2. authenticatorGetAssertion\n(replyingPartyInfo, clientDataHash)\n\n\n"];
  a rbox a [label="\n3. User verification, create assertion\n"];
  |||;
  a => c [label="4. authenticatorGetAssertionResponse\n(credentialId, authData, signature)\n\n\n"];
  c => s [label="5. authenticatorAssertionResponse\n(credentialId, clientData, authData, signature)\n\n\n"];
  s rbox s [label="\n6. Sever validation\n"];
  |||;
}
----

== Implementing

https://www.yubico.com/why-yubico/for-developers/developer-videos/[Watch FIDO2 / Web Authentication webinars] to learn more about the core concepts and how to integrate WebAuthn Relying Party operations into an authentication server.

link:/WebAuthn/WebAuthn_Developer_Guide/Overview.html[Read the dev guide] for an introduction to WebAuthn/FIDO2. The guide walks through this flow using Yubico's Java WebAuthn Server.

link:/FIDO2/Libraries/List_of_libraries.html[Integrate our open source libraries] and get started protecting user accounts with WebAuthn. Use these libraries to communicate with FIDO devices as well as verify attestation and assertion signatures.

The link:https://www.yubico.com/why-yubico/for-developers/developer-program[Yubico Developer Program] provides resources to enable rapid implementation of strong authentication. Resources include workshops, documentation, implementation guides, APIs, and SDKs.  Sign up to receive updates for our early access to the resources for implementing the FIDO2 and Web Authentication specifications.

link:https://www.yubico.com/why-yubico/for-developers/developer-program[Sign up now] for the Yubico Developer Program.

=== Attestation certificates

All Yubico FIDO devices use attestation certificates signed by the following root CA:
link:/u2f/yubico-u2f-ca-certs.txt[Yubico FIDO CA].

NOTE: If you have a YubiKey Preview device, the attestation certificate will 
instead be signed by our Preview CA: link:/u2f/fido-preview-ca-cert.pem[Yubico FIDO Preview CA].


== Useful Links

 - http://w3c.github.io/webauthn/[W3C Web Authentication specification]
 - https://www.w3.org/Webauthn/[W3C Web Authentication working group]
 - https://fidoalliance.org/specs/fido-v2.0-ps-20170927/fido-client-to-authenticator-protocol-v2.0-ps-20170927.html[FIDO2 Client to Authentication Protocol]
 - https://groups.google.com/a/fidoalliance.org/d/forum/fido-dev[FIDO-Dev Discussion List]

