== WebAuthn Walk-Through
Build an app that enables your users to register and authenticate through WebAuthn. To implement WebAuthn in your app, use the link:https://www.w3.org/TR/webauthn/[W3C Web Authentication API] specification and Yubico’s link:https://github.com/Yubico/java-webauthn-server/tree/master/webauthn-server-demo[Java WebAuthn Server].

=== Overview
With WebAuthn (also known as FIDO2), public-key cryptography is used to authenticate users to an online service, also known as a Relying Party (RP). When the end-user registers for an online service, an RP-specific credential key pair, i.e., a private key and a public key, is generated on the authenticator and the public key is sent to the RP (the private key never leaves the authenticator). When the user makes the request to log in, the authenticator sends an assertion that proves the user possesses the private key. The RP uses the public key to validate the assertion before allowing the user to log in.

With WebAuthn also comes the concept of a discoverable key credential (sometimes called link:http://WebAuthn_Developer_Guide/Resident_Keys.adoc["resident keys"]) stored on the authenticator instead of encrypted and stored on the server. Discoverable keys enable usernameless authentication scenarios.

For a detailed description of the registration and authentication ceremonies, see the “How it works” section of the link:WebAuthn_Developer_Guide/Overview.adoc[Overview] in the WebAuthn Developer Guide. In the same chapter, the sections immediately following, “FIDO2/WebAuthn application architecture” and “Key points” are also helpful.

In this document, we are going to walk through the Java-WebAuthn-Server's registration and authentication ceremonies and explain how the WebAuthn interaction works, step by step.


=== Prerequisites
You will need at least one YubiKey, plus installation of the following:

* **Yubico’s Java link:https://github.com/Yubico/java-webauthn-server/tree/master/webauthn-server-demo[WebAuthn Server demo]**
* **link:https://git-scm.com/[Git]**
* **link:https://github.com/Yubico/java-webauthn-server#dependency-configuration[Dependency configuration]** for Maven or Gradle
* **link:https://github.com/Yubico/java-webauthn-server/JavaDoc/webauthn-server-core/latest/com/yubico/webauthn/package-summary.html[Javadoc API documentation package-summary]** for the following
    ** link:https://developers.yubico.com/java-webauthn-server/JavaDoc/webauthn-server-core/latest/com/yubico/webauthn/CredentialRepository.html[Interface CredentialRepository]
    ** link:https://developers.yubico.com/java-webauthn-server/JavaDoc/webauthn-server-core/latest/com/yubico/webauthn/RelyingParty.html[Class RelyingParty]


=== Run Demo
To start the demo server, run the following in the `java-webauthn-server` directory:
....
./gradlew run
....
When the server is running, use a browser supporting WebAuthn and open https://localhost:5000 to access the website.

[NOTE]
======
You will get warnings in your browser about the connection not being secure. This is expected, because this server uses a self-signed certificate. You can safely proceed to the site.
======


=== Registration
The sequence of events in the registration flow is described in detail in the “Registration flow” section of the link:WebAuthn_Developer_Guide/WebAuthn_Client_Registration.adoc[WebAuthn Client Registration chapter] of the WebAuthn Developer Guide.


*Step 1* (Server) Implement the `CredentialRepository` interface. Look at the JavaDoc for link:https://github.com/Yubico/java-webauthn-server/JavaDoc/webauthn-server-core/latest/com/yubico/webauthn/CredentialRepository.adoc[`CredentialRepository`] and implement access logic for your database. Use the example link:https://github.com/Yubico/java-webauthn-server/JavaDoc/webauthn-server-core/latest/com/yubico/webauthn/CredentialRepository.html[`InMemoryRegistrationStorage`] as a reference.

*Step 2* (Server) Instantiate the library through the `RelyingParty` class. Include passing your `CredentialRepository` implementation as the argument to `.credentialRepository()`; for example:

....
RelyingPartyIdentity rpIdentity = RelyingPartyIdentity.builder()
    .id("example.com")
    .name("Example Application")
    .build();

RelyingParty rp = RelyingParty.builder()
    .identity(rpIdentity)
    .credentialRepository(new MyCredentialRepository())
    .build();
....

*Step 3* (Client) Initiate request to register an authenticator. User initiates account creation, or initiates new credential registration in account settings for an existing account.

*Step 4* (Client) Prepare ceremony parameters. RP instantiates `PublicKeyCredentialCreationOptions`.  See link:https://www.w3.org/TR/webauthn/#iface-pkcredential[`PublicKeyCredential Interface`] and link:https://www.w3.org/TR/webauthn/#credentialrequestoptions-extension[`CredentialRequestOptions`]; for example:

....
{
  "publicKey": {
    "attestation": "direct",
    "authenticatorSelection": {
      "authenticatorAttachment": "cross-platform",
      "requireResidentKey": false,
      "userVerification": "discouraged"
    },
    "challenge": "qNqrdXUrk5S7dCM1MAYH3qSVDXznb-6prQoGqiACR10=",
    "excludeCredentials": [],
    "pubKeyCredParams": [
      {
        "alg": -7,
        "type": "public-key"
      }
    ],
    "rp": {
      "id": "demo.yubico.com",
      "name": "Yubico Demo"
    },
    "timeout": 30000,
    "user": {
      "displayName": "Yubico demo user",
      "id": "bz9ZDfHzOBLycqISTAdWwWIZt8VO-6mT3hBNXS5jwmY="
    }
  }
}
....

*Step 5* (Client) Initiate request to register an authenticator. The App initiates registration ceremony. Call the JavaScript method `navigator.credentials.create()`. See link:https://www.w3.org/TR/webauthn/#createCredential[Create a new credential].

*Step 6* (Server) Respond with an instance. Construct a `StartRegistrationOptions` instance using its `.builder()`. Pass data to RP using `startRegistration` method, which returns `PublicKeyCredentialCreationOptions`. Store the `PublicKeyCredentialCreationOptions` temporarily as a pending request.


*Step 7* (Client) RP finalizes registration. The authenticator processes and returns to the browser the `attestationObject`. This includes a new public key, a credential ID, and attestation data. See link:https://www.w3.org/TR/webauthn/#iface-authenticatorattestationresponse[`AuthenticatorAttestationResponse`] and link:https://www.w3.org/TR/webauthn/#sctn-attestation-types[Attestation Types]. The `navigator.credentials.create()` method returns a promise resolving to a `PublicKeyCredential`. The `PublicKeyCredential` needs to be returned to the RP. See link:https://www.w3.org/TR/webauthn/#extensions[WebAuthn Extensions]. The RP parses the `PublicKeyCredential` to finalize registration; for example:

....
{
  "id": "X9FrwMfmzj...",
  "response": {
    "attestationObject": "o2NmbXRoZmlk...",
    "clientDataJSON": "eyJjaGFsbGVuZ..."
  },
  "clientExtensionResults": {}
}
....

The RP server stores the parsed credential ID, credential public key, and signature counter in the database. The RP should also provide an option to set a nickname for the newly registered credential. The RP may also store the `attestationObject` for future reference.

*Step 8* (Server) Finish the registration. Construct `PublicKeyCredential` from the JSON response using link:https://github.com/Yubico/java-webauthn-server/JavaDoc/webauthn-server-core/latest/com/yubico/webauthn/data/PublicKeyCredential.html#parseRegistrationResponseJson(java.lang.String)[`PublicKeyCredential.parseRegistrationResponseJson()`]. Retrieve and remove the `PublicKeyCredentialCreationOptions` from pending requests. Call `RelyingParty.finishRegistration()` and pass as arguments this `PublicKeyCredential` and the `PublicKeyCredentialCreationOptions` returned in the previous step.

*Step 9* (Server) Complete setup for use. Use `RegistrationResult` to update databases. Store `keyId` and `publicKeyCose` for use by `CredentialRepository`.

*Step 10* (Server) Process attestation. Store raw attestation object as part of credential; for example:

....
storeCredential("alice", result.getKeyId(),
result.getPublicKeyCose());
....

Use link:https://github.com/Yubico/java-webauthn-server/JavaDoc/webauthn-server-core/latest/com/yubico/webauthn/RegistrationResult.html#isAttestationTrusted()[`isAattestationTrusted()`], link:https://github.com/Yubico/java-webauthn-server/JavaDoc/webauthn-server-core/latest/com/yubico/webauthn/RegistrationResult.html#getAttestationType()[`getAttestationType()`] and link:https://github.com/Yubico/java-webauthn-server/JavaDoc/webauthn-server-core/latest/com/yubico/webauthn/RegistrationResult.html#getAttestationMetadata()[`getaAttestationMetadata()`] accessors to inspect attestation data and take action as dictated by your attestation policy fields.


=== Authentication
The sequence of events in the authentication flow is described in detail in the “Authentication Flow” section of the link:/WebAuthn_Developer_Guide/WebAuthn_Client_Authentication.adoc[Client Authentication] chapter of the WebAuthn Developer Guide.


*Step 1* (Client) Initiate request to RP. Request to authenticate on behalf of user.

*Step 2* (Client) Prepare ceremony parameters. RP returns challenge to client. See link:https://www.w3.org/TR/webauthn/#assertion-options[`PublicKeyCredentialRequestOptions` Assertion Generation]; for example:

....
{
  "publicKey": {
    "allowCredentials": [
      {
        "id": "X9FrwMfmzj...",
        "type": "public-key"
      }
    ],
    "challenge": "kYhXBWX0HO5GstIS02yPJVhiZ0jZLH7PpC4tzJI-ZcA=",
    "rpId": "demo.yubico.com",
    "timeout": 30000,
    "userVerification": "discouraged"
  }
}
....

*Step 3* (Client) Initiate request to authenticate with an authenticator. Call the JavaScript method `navigator.credentials.get()`. Browser in turn calls `authenticatorGetAssertion`. See link:https://www.w3.org/TR/webauthn/#getAssertion[Use Existing Credential] and link:https://www.w3.org/TR/webauthn/#op-get-assertion[`authenticatorGetAssertion` operation].


*Step 4* (Server) Initiate Authentication. Call: `RelyingParty` `startAssertion` method returns `AssertionRequest` and `PublicKeyCredentialRequestOptions`. Serialize `PublicKeyCredentialRequestOptions` to JSON and pass to `navigator.credentials.get()` method; for example:

....
AssertionRequest request = rp.startAssertion(StartAssertionOptions.builder()
    .username(Optional.of("alice"))
    .build());
String json = jsonMapper.writeValueAsString(request);
return json;
....

Store the `AssertionRequest` temporarily as a pending request.


*Step 5* (Client) RP finalize authentication. Authenticator matches credential with RP ID and returns `authenticatorData` and assertion signature to browser. Browser resolves the promise to a `PublicKeyCredential`. See link:https://www.w3.org/TR/webauthn/#iface-pkcredential[`PublicKeyCredential` interface]. RP parses `PublicKeyCredential` and finalizes authentication; for example:

....
{
  "id": "X9FrwMfmzj...",
  "response": {
    "authenticatorData": "xGzvgq0bVGR3WR0Aiwh1nsPm0uy085R0v-ppaZJdA7cBAAAACA",
    "clientDataJSON": "eyJjaGFsbG...",
    "signature": "MEUCIQDNrG..."
  },
  "clientExtensionResults": {}
}
....

Learn more: link:../WebAuthn_Developer_Guide/WebAuthn_Client_Authentication.adoc[WebAuthn Client Authentication chapter of the WebAuthn Developer Guide].


*Step 6* (Server) Finish Authentication. Construct `PublicKeyCredential` from client response using link:https://github.com/Yubico/java-webauthn-server/JavaDoc/webauthn-server-core/latest/com/yubico/webauthn/data/PublicKeyCredential.html#parseAssertionResponseJson(java.lang.String)[`PublicKeyCredential.parseAssertionResponseJson()`]. Retrieve and remove the `AssertionRequest` from pending requests. Wrap in `FinishAssertionOptions`, with `AssertionRequest`. Pass to RP using the `finishAssertion` method, which returns `AssertionResult`; for example:

....
String responseJson = /* ... */;

PublicKeyCredential<AuthenticatorAssertionResponse,
ClientAssertionExtensionOutputs> pkc =
PublicKeyCredential.parseAssertionResponseJson(responseJson);

try {
    AssertionResult result =
rp.finishAssertion(FinishAssertionOptions.builder()
        .request(request)
        .response(pkc)
        .build());

    if (result.isSuccess()) {
        return result.getUsername();
    }
} catch (AssertionFailedException e) { /* ... */ }
throw new RuntimeException("Authentication failed");
....

*Step 7* (Server) Post authentication complete steps for use. Initiate user session, using `username` and/or `userHandle`. Update stored signature count to `signatureCount` value in `AssertionResult`. Inspect warnings, if any.


== Test your App
Go through Yubico’s link:WebAuthn_Developer_Guide/Integration_Review_Standard_FIDO.adoc[integration review standard], if applicable. Review the WebAuthn/FIDO2 link:WebAuthn_Developer_Guide/WebAuthn_Readiness_Checklist.adoc[Readiness Checklist].


=== Additional Resources

* link:https://fidoalliance.org/specs/fido-v2.0-id-20180227/fido-client-to-authenticator-protocol-v2.0-id-20180227.html#authenticator-api[Client to Authenticator Protocol (CTAP) authenticator API]
* link:https://www.w3.org/TR/webauthn/[Web Authentication Public Key Credentials API]
* link:../Software_Projects/WebAuthn-FIDO2/WebAuthn-FIDO2_Server_Libraries/[WebAuthn FIDO2 Server Libraries]
* link:../Software_Projects/WebAuthn-FIDO2/WebAuthn-FIDO2_Host_Libraries/[WebAuthn FIDO2 Host Libraries]
* link:https://www.yubico.com/products/services-software/download/yubikey-manager/[YubiKey Manager]
