== Servers

[Note]
======
The U2F libraries are now deprecated and no longer maintained. We highly recommend transitioning to the FIDO2 libraries for enhanced security and compatibility.

C:: link:/libfido2/[libfido2]
Java:: link:/java-u2flib-server/[java-u2flib-server]
Python:: link:/python-fido2/[python-fido2]
\.NET:: link:/https://docs.yubico.com/yesdk//[.NET YubiKey SDK]

Learn more about link:/Passkeys[Passkeys], link:/WebAuthn[WebAuthn], and link:/CTAP[CTAP].
======

While it is quite easy to implement support for U2F by using a
link:/U2F/Libraries/Using_a_library.html[server library], it is sometimes
desirable to keep the U2F related logic outside of your application, making as
few modifications as possible to the application itself. For this reason we
have developed a U2F server, accompanied by a REST style API that we call _U2FVAL_.
The server provides U2F registration, authentication, storage of
registration data, and provides the client with metadata about the devices
used. This enables existing applications to enable multi-device U2F support
without needing to modify any existing database tables.

To get started with U2FVAL, check out our standalone link:/u2fval/[server], and
the link:U2FVAL_REST_API.html[REST API]. We also provide a number of connector
libraries, which make using the REST API even easier. You will find them
link:/Software_Projects/FIDO_U2F/U2FVAL_Connector_Libraries/[here].
