== GET OBJECT INFO

Get Object metadata.

== Description

Fetch all metadata about an link:../Concepts/Object.adoc[Object].

== Shell Example

Get Object info for Asymmetric Key with ID `0x1e15`:

  yubihsm> get objectinfo 0 0x1e15 asymmetric-key
  id: 0x1e15, type: asymmetric-key, algorithm: rsa2048, label: "rsakey", length: 896, domains: 1, sequence: 0, origin: imported, capabilities: sign-pkcs

== Protocol Details

=== Command

|===============
|T~c~ = 0x4e
|L~c~ = 2 + 1
|V~c~ = I \|\| T
|===============

I := link:../Concepts/Object_ID.adoc[Object ID] (2 bytes)

T := link:../Concepts/Object.adoc[Type] (1 byte)

=== Response

|==================================================
|T~r~ = 0xce
|L~r~ = 8 + 2 + 2 + 2 + 1 + 1 + 1 + 1 + 40 + 8
|V~r~ = C \|\| I \|\| N \|\| D \|\| T \|\| A \|\| S \|\| O \|\| L \|\| DC
|==================================================

C := link:../Concepts/Capability.adoc[Capabilities] (8 bytes)

I := link:../Concepts/Object_ID.adoc[Object ID] (2 bytes)

N := Object Length (2 bytes)

D := link:../Concepts/Domain.adoc[Domains] (2 bytes)

T := link:../Concepts/Object.adoc[Type] (1 byte)

A := link:../Concepts/Algorithms.adoc[Algorithm] (1 byte)

S := link:../Concepts/Sequence.adoc[Sequence] (1 byte)

O := Origin (1 byte)

L := link:../Concepts/Label.adoc[Label] (40 bytes)

DC := Delegated link:../Concepts/Capability.adoc[Capabilities] (8 bytes)
