= YUBIHSM-MANAGER(1)
:doctype:       manpage
:man source:    yubihsm-manager
:man version:   1.0.0

== NAME
yubihsm-manager - yubihsm-manager

== SYNOPSIS
*yubihsm-manager* [OPTIONS] [COMMAND]

== OPTIONS
*-k, --authkey*::
<authkey>      Authentication key to open a session with the device [default: 1]

*--privkey*::
<privkey>      Path to PEM file containing ECP256 private key used to open an asymmetric session

*-p, --password*::
<password>    Password to open a session with the device

*-C, --connector*::
<connector>  Connector URL [default: http://127.0.0.1:12345]

*-v, --verbose*::
Produce more debug output

*-h, --help*::
Print help

*-V, --version*::
Print version

*-r, --record*::
Record session operations in a script for later execution.

*-e, --exec*::
<file>                Execute operations from a recorded script file

*-s, --script-path*::
<script_name>  Path to a new script file. Use with --record. './yubihsm-manager_<timestamp>.json' if not set

*--mask*::
<mask>                Set masking level for recorded script. Masked values are prompted during script execution. [default: sensitive] [possible values: sensitive, all, none]

*--continue-on-error*::
Warn and skip failed operations during script execution instead of exiting.

== SUBCOMMANDS
*get-device-info*       Display YubiHSM device info +
*get-device-publickey*  Display YubiHSM device public key +
*asym*                  Manage and use asymmetric keys +
*sym*                   Manage and use symmetric keys +
*auth*                  Manage authentication keys (aka users) +
*wrap*                  Manage and use wrap keys +
*ksp*                   Setup KSP user for Windows CNG provider
*sunpkcs11*             Manage asymmetric keys compatible with JAVA SunPKCS11 provider
*reset*                 Reset YubiHSM2 device