== Known Issues and Limitations

The following issues are known to affect the current release.

=== USB Redirection in Virtual Machines

VM USB redirection may function inconsistently, particularly in Windows environments.

=== YubiHSM Shell

 - The yubihsm-shell utility is limited to reading 4096 bytes in a single command.

==== Unimplemented Commands When Invoked in Command-Line Mode

Yubihsm-shell when invoked in Command-Line mode (CLI) does not implement
the following commands (actions):

- put-option
- put-hmac
- put-otp-aead-key
- hmac
- benchmark
- otp-aead-create
- otp-decrypt
- version
- decrypt-oaep
- decrypt-ecdh
- sign-eddsa
- encrypt-aesccm
- decrypt-aesccm

=== YubiHSM 2 Setup Tool

Restore for non-shared wrapkey is currently not supported.

=== Attestation

Attestation currently does not support ed25519 keys.

=== Yhwrap Limitations

Currently yhwrap correctly wraps the following Object Types:

- Authkey
- Wrapkey
- Asymmetric
- Hmackey

The tool uses a catch-all for the rest which may not be correct.

=== PKCS#11 Module Limitations

- The PKCS#11 module does not support session objects
- The PKCS#11 module does not support C_DeriveKey(), that is ECDH
- The PKCS#11 module only supports symmetric encryption with CKM_YUBICO_AES_CCM_WRAP, no CKK_AES or CKM_AES_CBC
- The PKCS#11 module does not support asymmetric encryption
- CKA_ID can only be two bytes long on the device and is therefore truncated to that length
- CKA_LABEL is maximum 40 bytes
- C_InitPIN(), C_SetPIN & C_InitToken are not supported, equivalent operations have to be done through other interfaces (e.g., yubihsm-shell).
- C_CopyObject() & C_SetAttributeValue() are not supported, Objects are never modifiable after creation
