:imagesdir: ./Images

== Browser Compatibility ==
The Yubico WebAuthn Starter Kit supports authentication across a wide range of browsers and operating systems. However, as adoption of WebAuthn proceeds at different rates on different environments, some features and functions may not be supported.

The two methods of WebAuthn authentication supported by the Yubico WebAuthn Starter kit's Adaptive Multi-Factor Authentication flow are User-Verified and U2F with Password.

User-Verified authentication utilizes link:https://developers.yubico.com/WebAuthn/[WebAuthn discoverable credentials] protected with User-Verification on the WebAuthn authenticator. This can include WebAuthn PINs or Biometric identifiers. In this case, the PIN or Biometric resides and is verified directly on the WebAuthn Authenticator. However, not all platforms have built in support to register or authenticate with a WebAuthn PIN or Biometric.  For this use case, the browser must support both "Resident Key / Discoverable Credential" and "User Verification" in the table below.

U2F with Password authentication uses WebAuthn non-discoverable credentials, with a flow similar to link:https://developers.yubico.com/U2F[U2F Authentication]. To prevent unauthorized use of a U2F authenticator, the Yubico WebAuthn Starter Kit requires a Password to be submitted to the server on each use, where it is used to verify the authentication event comes from a legitimate user of the authenticator.  For this use case, the browser may support either "User Presence" or "CTAP 1 / U2F Legacy Support" in the table below.

These two use cases cover the majority of WebAuthn implementations. WebAuthn supports authentication over USB ports, as well as over NFC and other interfaces. For interested parties, the WebAuthn Starter kit can also be used as a test platform for checking if WebAuthn is supported on specific environments in general.

include::../../WebAuthn/WebAuthn_Browser_Support/index.adoc[tags=matrix]

For developers looking for additional information on WebAuthn support on browsers, refer to the link:Browser_WebAuthn_Support/index.html[WebAuthn Browser Support Matrix]
