== App ID

=== Terminology

Application::
A set of functionality provided by a common entity (the application owner), and
perceived by the user as belonging together. For example, _PayPal_ is an
application that allows users to pay for stuff.

Facets::
An (application) facet is how an application is implemented on various
platforms. For example, the application PayPal may have an Android app, an iOS
app, and a Web app. These are all facets of the PayPal application.

Facet ID::

A platform-specific identifier (URI) for an application facet.

 - For the Web, the Facet ID is the link:http://en.wikipedia.org/wiki/Same-origin_policy[web origin],
   written as a URI without a path (e.g. `https://login.paypal.com`).
 - For Android, the Facet ID is the URI `android:apk-key-hash:<hash-of-apk-signing-cert>`.
 - For iOS, the Facet ID is the URI `ios:bundle-id:<ios-bundle-id-of-app>`.

=== What should my AppID be?
The _Application ID_, or _AppID_, is a string that declares which facets that belong to this application.

==== Single-facet apps
If an app only has one facet the AppID can simply be the ID of that facet. For example:

	https://example.com


==== Multi-facet apps
If an app has many facets the AppID should be an HTTPS URL that resolves to a JSON list of facet IDs.
For example:

	https://example.com/app-id.json

...which could resolve to the following JSON content:

[source, javascript]
----
[
 "https://login.example.com",
 "android:apk-key-hash:2jmj7l5rSw0yVb/vlWAYkK/YBwk",
 "ios:bundle-id:com.example.app"
]
----


