== Implementing U2F using a library ==
Let us have a look at the U2F sequence diagram:

++++
<div class="diagram">
participant Token
participant Browser
Browser->Server: username and\npassword
Note over Server: verify username\nand password
Note over Server: generate U2F\nchallenge
Server->Browser: challenge (e.g. embedded\nin a HTML page)
Browser->Token: challenge
Note over Token: user touches\nbutton
Token-->Browser: response
Browser-->Server: response
Note over Server: verify response
</div>
++++




=== Client-side  ===
As shown in the diagram above, the main part of the client (web browser) is to
be a middle-man between the server and the hardware token.

Below is an example snippet using JQuery. The `u2f` object is provided by browsers that supports U2F.

[source, javascript]
/* u2f-login.html */
var challenge = // From the server (e.g. this row could be dynamically generated by the server)
$("#u2f-modal-dialog").show(); // Prompt user to touch token button
u2f.sign([challenge], [], // Forward challenge to token
  function(tokenResponse) {
	$('#u2f-form-data').val(JSON.stringify(tokenResponse));
	$('#u2f-form').submit(); // Send token response back to server
  }
);

When registering a new token `u2f.register` is used instead of `u2f.sign`.

== Available libraries ==
=== By Yubico ===

[options="header"]
|=======================
|Language    |Library 
|Java        |link:/Software_Projects/Java_Yubico[java-u2flib-client]
|Python      |link:/Software_Projects/Php_Yubico[python-u2flib-server]          
|=======================


pass::[<script src="jquery-1.11.1.min.js"></script><script src="raphael-min.js"></script><script src="underscore-min.js"></script><script src="sequence-diagram-min.js"></script><script>$(".diagram").sequenceDiagram({theme: 'simple'});</script>]

