== Windows API's

[Note]
======
We have officially announced the End of Life of the Windows COM APIs on February 19, 2025, in line with Yubico's https://www.yubico.com/support/terms-conditions/yubico-end-of-life-policy/[End-of-Life] policy. The Windows COM APIs will reach its End of Life on February 19, 2026.

For more details please visit our website for https://www.yubico.com/support/terms-conditions/yubico-end-of-life-policy/eol-products/[End-of-Life products].
======

Components based on Microsoft’s COM/ActiveX technology. See link:/windows-apis/Releases[releases] for installers and detailed documentation.

The x64 COM API installers do not register with Internet Explorer ActiveX components. Integrators and Developers looking to support the COM API in an Web-based environment are recommended to use the x86 (32-bit) version.

=== Windows Client COM API
The Client API for YubiKey 2.2 and later versions, featuring support for device serial numbers and challenge-response.

=== Windows Server COM API
Server support functionality for challenge-response, Yubico OTP and OATH-HOTP validation.
