== Prerequisites and Preparations

The audience of this document is an experienced system administrator with a good understanding of Microsoft SQL Server management. In addition, it is helpful to be familiar with the terminology, software and tools specific to YubiHSM 2. As a primer for these, refer to link:Terminology.adoc[the Terminology chapter].

In order to follow the steps provided in this guide, the following prerequisites must be met:

* Microsoft Windows Server 2012 SP2 or higher, with Microsoft .NET Framework 4.7.2 or higher. The operating system should be installed in a secure computer network. The system administrator must also have elevated system privileges.

* Access to Microsoft SQL Server 2017 with SQL Server Management Studio (SSMS) 2017 or higher.

* YubiHSM 2 software and tools for Windows downloaded from link:../../Releases[the Yubico YubiHSM 2 Release page] and available on the system to be used.

[NOTE]
======
The 32-bit version of the YubiHSM KSP DLL is needed for use with SSMS.
======

* Two (2) link:https://www.yubico.com/products/yubihsm/[YubiHSM 2 devices], one for deployment and one for backup in hardware.

* Your organization policies may require key custodians to be available for the YubiHSM 2 deployment. For more information about key custodians and the associated ‘M of N’ key shares, see "Understanding Key Splitting and Key Custodians" in link:../YubiHSM_2_Windows_Deployment_Guide\--Configure_YubiHSM_2_Key_Storage_Provider_for_Microsoft_Windows_Server/Prerequisites_and_Preparations.adoc["Prerequisites and Preparations" in the YubiHSM 2 Windows Deployment Guide].


=== Configuration for this Integration

For the integration described in this guide, the following hardware and software configuration was used:

* Microsoft Windows Server 2012 SP2.

* Microsoft .NET Framework 4.7.2.

* Microsoft SQL Server 2017.

* Microsoft SQL Server Management Studio (SSMS) 2018.

* Yubico YubiHSM v 2.1.2.

* Yubico YubiHSM software tools v TBD. In particular, the 32-bit YubiHSM KSP DLL is needed for use with SSMS (which is a 32-bit application).


link:Basic_Setup_of_YubiHSM_2_and_SQL_Server.adoc[Next: Basic Setup of YubiHSM 2 and SQL Server]
