== Yubico OTP Integration Plug-ins
These plug-ins enable you to integrate Yubico OTP support into existing systems.

PAM module:: link:/yubico-pam[yubico-pam]
Windows login:: link:/https://github.com/Yubico/yubico-windows-auth[yubico-windows-auth] is deprecated and no longer maintained
YubiAuth:: link:/https://github.com/Yubico/yubiauth[yubiauth] is deprecated and no longer maintained
FreeRADIUS:: link:/https://github.com/Yubico/rlm-yubico[rlm-yubico] is deprecated and no longer maintained
Shibboleth:: link:/https://github.com/Yubico/yubico-shibboleth-idp-multifactor-login-handler[yubico-shibboleth] is deprecated and no longer maintained
JAAS:: link:/https://github.com/Yubico/yubico-java-client[yubico-java-client] is deprecated and no longer maintained

Third party plugins can be discovered on link:https://github.com/search?q=yubico+otp[GitHub] for example.

[Note]
======
Yubico has declared end-of-life for the YubiKey Validation Server (YK-VAL) and YubiKey Key Storage Module (YK-KSM). These have been moved to link://github.com/YubicoLabs/yubikey-ksm[YubicoLabs] as a reference architecture. See article, link:/support.yubico.com/hc/en-us/articles/360021227000[YK-VAL, YK-KSM and YubiHSM 1 End-of-Life].
======
