= YUBIHSM-SETUP(1)
:doctype:       manpage
:man source:    yubihsm-setup
:man version:   2.2.0

== NAME
yubihsm-setup - yubihsm-setup

== SYNOPSIS
*yubihsm-setup* [FLAGS] [OPTIONS] <SUBCOMMAND>

== OPTIONS
*-h, --help*::
Prints help information

*-d, --no-delete*::
Do not delete the authentication key when done

*-e, --no-export*::
Do not export under wrap the application objects

*-a, --no-new-authkey*::
Use this flag if you want to generate an asymmetric key and self-signed certificate on the
YubiHSM for use with EJBCA

*-V, --version*::
Prints version information

*-v, --verbose*::
Produce more debug output

*-k, --authkey*::
<authkey>        Authentication key to open a session with the device [default: 1]

*-c, --connector*::
<connector>    Connector URL [default: http://127.0.0.1:12345]

*-p, --password*::
<password>      Password to open a session with the device

== SUBCOMMANDS
*dump*        Dump wrapped objects +
*ejbca*       Setup for EJBCA usage +
*help*        Prints this message or the help of the given subcommand(s) +
*ksp*         Setup for ADCS usage +
*reset*       Reset the device +
*restore*     Restore or setup additional devices +
