== Options

Options are device-global settings. The following Options are defined:

[options="header"]
|=======================
|Option Name | Hex Value
|force-audit | 0x01
|command-audit | 0x03
|=======================


The data payload is Option-specific.

=== Force Audit
This Option is used to enable Force Audit mode which prevents the device from performing additional operations whilst the link:Logs.adoc[Log Store] is full.

The Option accepts three different values:
- 0x00: Option disabled
- 0x01: Option enabled
- 0x02: Option permanently enabled (not possible to turn off)

=== Command Audit
This Option is used to enable or disable logging of specific commands. Logging commands has a noticeable impact on performance. By default logging is enabled for all operations.

The Option accepts three different values:
- 0x00: Option disabled
- 0x01: Option enabled
- 0x02: Option permanently enabled (not possible to turn off)

Multiple commands can be specified at once with the syntax `C1 V1, C2 V2, ..., Cn Vn` where `Ci` is the Command Code and `Vi` is the Option Value. An example of this syntax can be found at the link:../Commands/Set_Option.adoc[Set Option] Command description.
