== Session

A Session is not a property of a specific Object, but rather it is used to describe a logical connection between an application and a device. Sessions are end-to-end encrypted and authenticated using session-keys. Those keys are derived from long-lived, pre-shared Authkey Objects as part of the sessions authentication process. The Session creation and authentication protocol is based on Global Platform SCP03.

On a single YubiHSM 2 it is possible to establish up to `16` independent and concurrent Sessions. Note that while multiple concurrent Sessions are "alive" at a given time, the device still serves as a rendezvous point. This means that time-consuming operations, like generating a long RSA key, will block commands on other parallel Sessions. Session are addressed with a number in the range `[0-15]`.

Sessions have an expiration period of `30` seconds of inactivity in order to prevent resource starvation. After such a period, the device will consider a Session inactive and will move it to the pool of re-usable Sessions. Whenever a command is executed on a given Session, the inactivity timer is reset, meaning that if a Session is being constantly used then it will not expire.

Some of the operations that can be performed on a YubiHSM 2 do _not_ require a Session. The implications are that the command and its response will travel unencrypted to and from the device. These commands are only demonstrations and generic status commands, making Sessions effectively necessary for any meaningful operation.

The long-lived keys required to derive Sessions can be explicitly used in the relevant commands. There are however built-in functionality to derive those keys from a password using `10,000` iterations or `PBKDF2` with the salt `Yubico`, making the process more human-friendly. *Every new or factory-reset YubiHSM 2 has a default Authkey with ID 1 and all Capabilities and all Domains set*. This is equivalent to a superuser or an administrator. The long-lived keys for this Object are derived using the process described before with the password `password`.

WARNING: *It is important to delete this well-known password before deployment*.
