== Attestation
When creating the key pair, there is an option to request the attestation certificate. This optional information can be sent to the relying party as part of the registration process. The attestation is how authenticators prove to the relying party that the keys they generate originate from a genuine device with certified characteristics and establish a hardware root of trust. 

If your service does not have specific needs for attestation information, well defined policy for what to do with it and why, you should not verify authenticator attestations. The reasons for this is that it takes more work for the RP to do, your users may not be able to use the authenticator(s) they have, and you risk being incompatible with future authenticators unless you keep your attestation certificate store up to date. On the other hand, you should store the verbatim navigator.credentials.create() request and the PublicKeyCredential response, including the attestation statement, so that you can retroactively inspect registrations when policy changes.

The rest of this section assumes that you need authenticator attestation. If you don’t, you can ignore the rest of this section.

Relying parties should collect, store, and validate attestation certificates. Attestation certificates contain metadata such as the device name, supported transports, image url, etc. This metadata can be retrieved by the RP to enable granular attestation certificate authority management, customize user experiences based on supported transports, and report authenticator metrics in your environment. Additionally, a trust store containing all registered attestation certificates provides an audit trail to support high assurance MFA.

Attestation signatures are actually disabled by default in WebAuthn. The reason for this is that most sites probably just want something better than traditional single-factor password authentication and are not concerned with how the authenticator is implemented. This also means they do not need to maintain an up-to-date trust store in order to support new authenticators entering the market. So for these reasons, the browser will actually not return the attestation signature unless the relying party specifically asked for it. And as a relying party, if you do not need the higher guarantees that the attestation signature provides, it can be ignored.

But it's important to note that if you ignore the attestation signature, there is no guarantees about the security properties of the authenticator. So if you need high assurance MFA, it is not appropriate to ignore the attestation signature, because then there is no guarantee that the authenticator actually does the multi-factor verification, even if it claims that it does.

The way you enable attestation signatures is by setting the `PublicKeyCredentialCreationOptions.attestation` parameter to the value ‘direct’ when you make the call to register a new credential.

link:Resident_Keys.html[Next: Resident Keys]