== Desktop and Mobile Authentication
=== Desktop App/Platform Authentication
Yubico’s https://github.com/Yubico/libfido2[libfido2] and https://github.com/Yubico/python-fido2[python-fido2] open source libraries provide examples for how to communicate with a FIDO device over USB, and can verify attestation and assertion signatures. Both FIDO U2F (CTAP1) and FIDO2 (CTAP2) protocols are supported on Linux, MacOS, and Windows platforms.

https://blogs.windows.com/msedgedev/2018/07/30/introducing-web-authentication-microsoft-edge/#UZcrEz8uWr1dcz0R.97[Microsoft Edge announced Web Authentication support] which enables FIDO2 devices or Windows Hello users to authenticate without any password on any Windows 10 device, using biometrics or a PIN. The https://docs.microsoft.com/en-us/microsoft-edge/dev-guide/windows-integration/web-authentication[Web Authentication and Windows Hello dev guide] will walk through the flow. This guide highlights how to detect if Windows Hello is available on a PC. It also explains how to set the authenticatorAttachment parameter for the best user experience when registering a FIDO2 capable platform, such as Windows 10.

=== Mobile App/Platform Authentication

==== iOS
For developers currently supporting FIDO2 security keys using the WebAuthn standard on desktop browsers, checkout this guide https://developers.yubico.com/WebAuthn/Supporting_U2F_or_FIDO2_Security_Keys_on_iOS_or_iPadOS/[Supporting U2F or FIDO2 Security Keys on iOS and iPadOS].

If you wish to interact with a YubiKey via other protocols or want a custom user experience, Yubico provides an iOS SDK for integration into native App Store apps.

Get started with the Yubico iOS SDK https://github.com/Yubico/yubikit-ios[here].

==== Android
Native support for WebAuthn and FIDO is finally here for Android. Yubico provides a comprehensive library for developers to interact with YubiKeys from their Android applications.

Get started with the Yubico Android SDK https://github.com/Yubico/yubikit-android[here].

link:Integration_Review_Standard_FIDO.html[Next: Integration Review Standard - FIDO]
