== Desktop and Mobile Authentication
=== Desktop App/Platform Authentication
Yubico’s https://github.com/Yubico/libfido2[libfido2] and https://github.com/Yubico/python-fido2[python-fido2] open source libraries provide examples for how to communicate with a FIDO device over USB, and can verify attestation and assertion signatures. Both FIDO U2F (CTAP1) and FIDO2 (CTAP2) protocols are supported on Linux, MacOS, and Windows platforms.

https://blogs.windows.com/msedgedev/2018/07/30/introducing-web-authentication-microsoft-edge/#UZcrEz8uWr1dcz0R.97[Microsoft Edge announced Web Authentication support] which enables FIDO2 devices or Windows Hello users to authenticate without any password on any Windows 10 device, using biometrics or a PIN. The https://docs.microsoft.com/en-us/microsoft-edge/dev-guide/windows-integration/web-authentication[Web Authentication and Windows Hello dev guide] will walk through the flow. This guide highlights how to detect if Windows Hello is available on a PC. It also explains how to set the authenticatorAttachment parameter for the best user experience when registering a FIDO2 capable platform, such as Windows 10.

=== Mobile App/Platform Authentication
==== Android
You can find the https://developers.google.com/android/reference/com/google/android/gms/fido/fido2/api/common/package-summary[Android APIs for FIDO2 here].

==== iOS
FIDO2 and WebAuthn support via mobile browsers on iOS are still under development.

link:/WebAuthn/WebAuthn_Developer_Guide/integration-review-standard-fido.html[Next: Integration Review Standard - FIDO]
