== Resident Keys
WebAuthn enables high assurance multi-factor authentication with a passwordless login experience. One of the things that enables this is what is called resident keys.

Resident key means that the private key is stored in persistent memory on the authenticator, instead of encrypted and stored on the relying party server. If the key is stored on the server, then the server needs to return that to the authenticator before the authenticator can decrypt and use it. This means that the user needs to provide a username, and usually also a password, before the server can do that.

With resident keys, the private key is stored on the authenticator. This means that the user does not need to enter a username to login. This is achieved through the user handle, via the `user.id` property in `PublicKeyCredentialCreationOptions`.  The RP generates a user handle which is stored in the resident key on the authenticator during the registration ceremony. Then during the authentication ceremony the authenticator returns the user handle allowing the RP to look up the associated user.

A username-less flow might look something like this: The user goes to the login page, plugs in the authenticator, and taps the button, and then they are logged in. This is called a “first-factor” authentication. If the authenticator also supports PIN or biometric verification, you can get high assurance multi-factor authentication in a single login step with no passwords sent over the wire.

link:Algorithms.html[Next: Algorithms]
