== Mobile SDK

=== Get Started with the YubiKey 5Ci

The YubiKey 5Ci is a multi-protocol security key equipped with FIDO2/WebAuthn, FIDO U2F, OTP (one-time password), PIV (Smart Card), and OpenPGP. With support for multiple authentication protocols, the YubiKey 5Ci delivers strong multi-factor, second-factor (2FA), and single-factor passwordless authentication for a simple and seamless user experience across the entire computing ecosystem.

=== Download the latest Mobile SDK for YubiKey 5C NFC 

The newly announced YubiKey 5C NFC and updated Mobile SDK with NFC will provide yet another authentication option for all environments supporting iOS, Android, Windows, macOS, and more, all on one key. Arriving this coming Winter, this new device will deliver the same multi-protocol functionality and user experience of the YubiKey 5 Series. Be notified when the key and updated Mobile SDK with NFC are available by submitting the form link:Sign_Up_For_Updates[here]. 

=== Yubico Mobile iOS SDK

The Yubico Mobile iOS SDK is an iOS library provided by Yubico to interact with YubiKeys on iOS devices.

* https://github.com/Yubico/yubikit-ios/releases[Download iOS SDK]

Starting from version 2.0.0, YubiKit adds support for YubiKeys with lightning connector, such as the YubiKey 5Ci, a security key design by Yubico for iOS devices.

The library supports NFC-enabled YubiKeys and provides the APIs to request an OTP (Yubico OTP or HOTP) from the NFC YubiKeys using a NFC-enabled iOS device. It also provides a built-in QR Code reader which can be used as an alternative enrolment mechanism for iOS devices which don't support NFC reading.

The library is provided with a demo application which shows a complete example of how to integrate and use all the features of the library in an iOS project.

=== Get Started

Pick up a https://www.yubico.com/product/yubikey-5ci[YubiKey 5Ci here] if you don’t already have one. 

Use the https://github.com/YubicoLabs/YubiKit-iOS-Starter[iOS Swift starter app] to learn how to integrate the Yubico SDK for iOS with your app.

Ready to get started? Watch our Technical Overview video https://www.youtube.com/watch?v=FpcC-9BLgDA[here] to get an idea of the process from start to finish. If you run into any issues during the process, fill out a developer https://support.yubico.com/support/tickets/new[support ticket] and our team will be able to assist you.

=== Yubico Mobile Android SDK

* https://github.com/YubicoLabs/yubikit-android[Download Android SDK]

This is a pre-release, beta version of the Yubico Mobile Android SDK. Some of the specs and APIs may change in future releases so use this documentation and the library for prototyping and not for public release. If you are an early adopter please provide detailed feedback about the design and issues you may find when using YubiKit.

=== FAQs

*What protocols will the YubiKey 5C NFC support?*

The current preview device supports FIDO U2F, FIDO2, smart card (PIV), Yubico OTP, OpenPGP, OATH-TOTP, OATH-TOTP, and Challenge-Response.

*What is the minimum version of the iOS SDK required for WebAuthn over NFC?*

WebAuthn over NFC is coming to the iOS SDK version 3.0. Sign up link:Sign_Up_For_Updates[here] to be notified of updates to the SDK.

*How can I be notified when the WebAuthn NFC version of the SDK is available for BETA?*

Sign up link:Sign_Up_For_Updates[here] to be notified of updates to the SDK.

*Is the iOS SDK required to implement the NFC capability in my app?*

Yes. The Yubico iOS SDK will provide the low-level NFC APDU communication.

*Do I need to register my app with Yubico when using the iOS NFC capabilities with NFC YubiKeys?*

If your app only supports the NFC communication you don’t need to register the app with Yubico. If you plan to support the YubiKey 5Ci via the Lightning connector, you do need to register with Yubico as the YubiKey 5Ci is an Apple MFi External Accessory.

*Will my WebAuthn site work on Mobile Safari for iOS 13?*

As of iOS 13.1, Safari mobile browser on iOS does not support WebAuthn. Check out the Brave browser for iOS as they have built-in support for WebAuthn and the YubiKey 5Ci.

*What features of the YubiKey will be supported in the next version of the iOS SDK?*

In addition to supported FIDO U2F, FIDO2, smart card (PIV), Yubico OTP, OpenPGP, OATH-TOTP, OATH-HOTP, and Challenge-Response features over the Lightning connector, the next version of iOS SDK will support FIDO2/WebAuthn over NFC.