== Mobile SDK

=== Get Started with the YubiKey 5Ci

The YubiKey 5Ci is a multi-protocol security key equipped with FIDO2/WebAuthn, FIDO U2F, OTP (one-time password), PIV (Smart Card), and OpenPGP. With support for multiple authentication protocols, the YubiKey 5Ci delivers strong multi-factor, second-factor (2FA), and single-factor passwordless authentication for a simple and seamless user experience across the entire computing ecosystem.

=== Yubico Mobile iOS SDK

The Yubico Mobile iOS SDK is an iOS library provided by Yubico to interact with YubiKeys on iOS devices.

* https://github.com/Yubico/yubikit-ios[Download iOS SDK]

Starting from version 2.0.0, YubiKit adds support for YubiKeys with lightning connector, such as the YubiKey 5Ci, a security key design by Yubico for iOS devices.

The library supports NFC-enabled YubiKeys and provides the APIs to request an OTP (Yubico OTP or HOTP) from the NFC YubiKeys using a NFC-enabled iOS device. It also provides a built-in QR Code reader which can be used as an alternative enrolment mechanism for iOS devices which don't support NFC reading.

The library is provided with a demo application which shows a complete example of how to integrate and use all the features of the library in an iOS project.

Ready to get started? Watch our Technical Overview video https://www.youtube.com/watch?v=FpcC-9BLgDA[here] to get an idea of the process from start to finish. If you run into any issues during the process, fill out a developer https://support.yubico.com/support/tickets/new[support ticket] and our team will be able to assist you.

=== Yubico Mobile Android SDK

* https://github.com/YubicoLabs/yubikit-android[Download Android SDK]

This is a pre-release, beta version of the Yubico Mobile Android SDK. Some of the specs and APIs may change in future releases so use this documentation and the library for prototyping and not for public release. If you are an early adopter please provide detailed feedback about the design and issues you may find when using YubiKit.




