== Copyrights and Contacts

=== Copyright

© 2021 Yubico AB. All rights reserved.


==== Trademarks

Yubico and YubiKey are registered trademarks of Yubico AB. All other trademarks are the property of their respective owners.


=== Disclaimer


The contents of this document are subject to revision without notice due to continued progress in methodology, design, and manufacturing. Yubico shall have no liability for any error or damages of any kind resulting from the use of this document.

The Yubico Software referenced in this document is licensed to you under the terms and conditions accompanying the software or as otherwise agreed between you or the company that you are representing.

=== Contact Information

|===================
|Yubico Inc. \|
 530 Lytton Street \|
 Suite 301 \|
 Palo Alto, CA 94301 \|
 USA
|===================



link:https://www.yubico.com/support/contact/[Yubico Support]

More options for getting touch with us are available on the Contact page of Yubico’s website.


=== Document Updated

January 2021
