== Getting Started with iOS

Native support for WebAuthn and FIDO is finally here on iPhones and iPads. Yubico now offers two great user experiences on iOS using a simple tap or a physical connection. Authentication via NFC is supported by the https://www.yubico.com/product/yubikey-5-nfc[YubiKey 5 NFC] or https://www.yubico.com/product/security-key-nfc-by-yubico[Security Key NFC] by Yubico by just tapping the YubiKey at the top of an iPhone (7 and above). Authentication via physical connection is supported by the https://www.yubico.com/product/yubikey-5ci[YubiKey 5Ci] by plugging the YubiKey into the Lightning or USB-C port of an iPhone or iPad.

NOTE: For developers currently supporting FIDO2 security keys using the WebAuthn standard on desktop browsers, checkout this guide https://developers.yubico.com/WebAuthn/Supporting_U2F_or_FIDO2_Security_Keys_on_iOS_or_iPadOS/[Supporting U2F or FIDO2 Security Keys on iOS and iPadOS]

The above article covers two paths that developers can take for supporting YubiKeys on mobile.

*1.* Using the native iOS/iPadOS libraries and mobile Safari browser as of iOS 13.3 or 

*2.* Use the Yubico iOS SDK integrated into a native app to support other features available on a YubiKey.

For path #2, get started with the Yubico iOS SDK below.

If you run into any issues during the development process, fill out a https://support.yubico.com/support/tickets/new[developer support ticket] and our team will be happy to assist you.

=== Yubico iOS SDK

The Yubico Mobile iOS SDK is an iOS library provided by Yubico to interact with YubiKeys on iOS devices.

* https://github.com/Yubico/yubikit-ios[Download iOS SDK]

The library supports NFC-enabled YubiKeys and the Lightning connector YubiKey 5Ci. This library provides the APIs to interact with the following features of a YubiKey:

https://github.com/Yubico/yubikit-ios/blob/master/docs/fido2.md[FIDO] - Provides FIDO2 operations accessible via the YKFKeyFIDO2Service.

https://github.com/Yubico/yubikit-ios/blob/master/docs/u2f.md[U2F] - Provides U2F operations accessible via the YKFKeyU2FService.

https://github.com/Yubico/yubikit-ios/blob/master/docs/oath.md[OATH] - Allows applications, such as an authenticator app to store OATH TOTP and HOTP secrets on a YubiKey and generate one-time passwords.

https://github.com/Yubico/yubikit-ios/blob/master/docs/otp.md[OTP] - Provides implementation classes to obtain YubiKey OTP via accessory (5Ci) or NFC.

https://github.com/Yubico/yubikit-ios/blob/master/docs/raw.md[RAW] - Allows sending raw commands to YubiKeys over two channels: YKFKeyRawCommandService or over a PC/SC like interface.

https://github.com/Yubico/yubikit-ios/blob/master/docs/chr.md[Challenge-response] - Provides a method to use HMAC-SHA1 challenge-response.

In addition, the library provides a https://github.com/Yubico/yubikit-ios/tree/master/YubiKitDemo[demo application] which shows a complete example of how to integrate and use all the features of the library in an iOS project.

=== Get Started

Pick up a https://www.yubico.com/product/yubikey-5ci[YubiKey 5Ci here] or https://www.yubico.com/product/yubikey-5-nfc[YubiKey 5 NFC] if you don’t already have one of these keys. 

Use the https://github.com/YubicoLabs/YubiKit-iOS-Starter[iOS Swift starter app] to learn how to integrate the Yubico SDK for iOS with your app or checkout the https://github.com/Yubico/yubikit-ios/tree/master/YubiKitDemo[Yubico Demo App] provided as part of the iOS SDK.