== Get Started with the YubiKey 5Ci

=== The Yubico Mobile iOS SDK is an iOS library provided by Yubico to interact with YubiKeys on iOS devices.

The library supports NFC-enabled YubiKeys and provides the APIs to request an OTP (Yubico OTP or HOTP) from the NFC YubiKeys using a NFC-enabled iOS device. It also provides a built-in QR Code reader which can be used as an alternative enrolment mechanism for iOS devices which don't support NFC reading.

Starting from version 2.0.0, YubiKit adds support for YubiKeys with lightning connector, such as the YubiKey 5Ci, a security key design by Yubico for iOS devices.

The library is provided with a demo application which shows a complete example of how to integrate and use all the features of the library in an iOS project.

Ready to get started? Watch our Technical Overview video to get an idea of the process from start to finish. Or dive right in and download the SDKs from the links below. If you run into any issues during the process, fill out a developer support ticket and our team will be able to assist you.

. https://github.com/YubicoLabs/yubikit-ios/releases/download/2.0.0-RC1/YubiKit_2_0_0_RC1.zip[Download iOS SDK]
. https://github.com/YubicoLabs/yubikit-ios[Download Source Code]
. https://github.com/YubicoLabs/yubikit-android[Download Android SDK]
