== Software Signing

Yubico aims to cryptographically sign all software that it distributes.
We use three different techniques to achieve this.

=== OpenPGP Software Signing

Source code releases are usually signed by an OpenPGP key of one of
Yubico's developers.  Some ZIP files containing Windows executables are
also signed using OpenPGP.

Please find below the list of Yubico developers making releases.

- Simon Josefsson <simon@yubico.com>
link:54265e8c.asc[`9AA9 BDB1 1BB1 B99A 2128  5A33 0664 A769 5426 5E8C`]

- Klas Lindfors <klas@yubico.com>
link:b2168c0a.asc[`0A3B 0262 BCA1 7053 07D5  FF06 BCA0 0FD4 B216 8C0A`]

- Dain Nilsson <dain@yubico.com>
link:6fba95e8.asc[`20EE 325B 86A8 1BCB D3E5  6798 F043 6709 6FBA 95E8`]

- Henrik Stråth <henrik@yubico.com>
link:958e0658.asc[`DCB9 04FA B343 CFA7 1907  6EF7 9EA9 0242 958E 0658`]

- Alessio Di Mauro <alessio@yubico.com>
link:0a7c787e.asc[`4133 1A83 E892 DC83 AD70  4E8D 245C 7396 0A7C 787E`]

- Tommaso De Orchi <tom@yubico.com>
link:a0973948.asc[`FF8A F719 AE58 2818 1B89  4D83 1CE3 9268 A097 3948`]


=== Windows Software Signing

Our Windows executables are signed with a code signing certificate,
issued by GoDaddy.

link:yubico-windows-code.pem[]

SHA256 fingerprint:: `1F:DA:33:2D:C3:DB:B7:DA:13:1B:BE:78:6E:2E:F9:2C:40:86:59:08:E5:C8:AA:1C:FC:F7:C6:5F:35:37:E3:7E`

Windows software released before 2015-03-12 is instead signed with:

link:yubico-windows-code-old.pem[]

SHA256 fingerprint:: `DB:75:AF:B8:AF:DF:5C:DC:F9:70:1E:0E:FA:4C:44:97:ED:BE:0D:95:DB:8D:12:82:77:23:C6:6B:69:FE:3E:8B`


=== Mac Software Signing

Our Mac executables are signed with a Yubico code signing certificate,
issued by Apple.

link:yubico-mac-code.pem[]

SHA256 fingerprint:: `F4:EC:6D:AF:9A:E6:AD:49:F6:D3:99:9A:D8:92:8E:A1:D3:A9:45:94:15:90:BC:33:BA:9D:8E:35:59:02:3C:BD`
