== Software Signing

Yubico aims to cryptographically sign all software that it distributes.
We use three different techniques to achieve this.

=== OpenPGP Software Signing

Source code releases are usually signed by an OpenPGP key of one of
Yubico's developers.  Some ZIP files containing Windows executables are
also signed using OpenPGP.

Following are the keys for Yubico developers who are currently releasing code.

- Klas Lindfors <klas@yubico.com>
link:https://pgp.mit.edu/pks/lookup?op=vindex&search=0x0a3b0262bca1705307d5ff06bca00fd4b2168c0a[`0A3B 0262 BCA1 7053 07D5  FF06 BCA0 0FD4 B216 8C0A`]

- Dain Nilsson <dain@yubico.com>
link:https://pgp.mit.edu/pks/lookup?op=vindex&search=0x20ee325b86a81bcbd3e56798f04367096fba95e8[`20EE 325B 86A8 1BCB D3E5  6798 F043 6709 6FBA 95E8`]

- Alessio Di Mauro <alessio@yubico.com>
link:https://pgp.mit.edu/pks/lookup?op=vindex&search=0xb70d62aa6a31ad6b9e4f9f4bdc8888925d25ca7a[`B70D 62AA 6A31 AD6B 9E4F  9F4B DC88 8892 5D25 CA7A`]

- Tommaso De Orchi <tom@yubico.com>
link:https://pgp.mit.edu/pks/lookup?op=vindex&search=0xff8af719ae5828181b894d831ce39268a0973948[`FF8A F719 AE58 2818 1B89  4D83 1CE3 9268 A097 3948`]

- Jean Paul Galea <jeanpaul@yubico.com>
link:https://pgp.mit.edu/pks/lookup?op=vindex&search=0xb6042e2bd1fdbc2bca8588b2ff8d3b45b7b875a9[`B604 2E2B D1FD BC2B CA85  88B2 FF8D 3B45 B7B8 75A9`]

- Dag Heyman <dag@yubico.com>
link:https://pgp.mit.edu/pks/lookup?op=vindex&search=0x8d0b4eba9345254bcec0e843514f078ff4ab24c3[`8D0B 4EBA 9345 254B CEC0  E843 514F 078F F4AB 24C3`]

- Emil Lundberg <emil@yubico.com>
link:https://pgp.mit.edu/pks/lookup?op=vindex&search=0x57a9deed4c6d962a923bb691816f3ed99921835e[`57A9 DEED 4C6D 962A 923B  B691 816F 3ED9 9921 835E`]

- Trevor Bentley <trevor@yubico.com>
link:https://pgp.mit.edu/pks/lookup?op=vindex&search=0x268583b64786f50f807456da8ced3a80d41c0dcb[`2685 83B6 4786 F50F 8074  56DA 8CED 3A80 D41C 0DCB`]

- Pedro Martelletto <pedro@yubico.com>
link:https://pgp.mit.edu/pks/lookup?op=vindex&search=0xee90ae0d19774c8386628faab428949ef7914718[`EE90 AE0D 1977 4C83 8662  8FAA B428 949E F791 4718`]

- Aveen Ismail <aveen.ismail@yubico.com>
link:https://pgp.mit.edu/pks/lookup?op=vindex&search=0x1d7308b0055f5aef36944a8f27a9c24d9588ea0f[`1D73 08B0 055F 5AEF 3694 4A8F 27A9 C24D 9588 EA0F`]

Following are the keys for developers who have released code in the past.

- Simon Josefsson <simon@yubico.com>
link:https://pgp.mit.edu/pks/lookup?op=vindex&search=0x9aa9bdb11bb1b99a21285a330664a76954265e8c[`9AA9 BDB1 1BB1 B99A 2128  5A33 0664 A769 5426 5E8C`]

- Henrik Stråth <henrik@yubico.com>
link:https://pgp.mit.edu/pks/lookup?op=vindex&search=0xdcb904fab343cfa719076ef79ea90242958e0658[`DCB9 04FA B343 CFA7 1907  6EF7 9EA9 0242 958E 0658`]


=== Windows Software Signing

Our Windows executables are signed with one of two code signing certificates,
issued by GoDaddy and one issued by DigiCert:

link:yubico-windows-code-digicert.pem[]

SHA256 fingerprint:: `C3:C1:BE:40:B7:F2:C7:B2:51:DB:67:35:88:40:76:9F:37:35:28:D2:5E:32:AD:0D:80:6F:01:C6:ED:96:E8:2D`

link:yubico-windows-code-godaddy.pem[]

SHA256 fingerprint:: `43:9D:B8:FB:32:F3:BA:47:15:5C:BA:E5:8A:02:A5:02:B3:ED:15:7A:34:23:B8:62:74:6E:20:AE:17:7F:5C:ED`

Windows software released before 2018-03-12 is signed with:

link:yubico-windows-code-2017.pem[]

SHA256 fingerprint:: `42:77:C7:17:01:5F:DB:6F:EA:CC:5D:4B:69:BD:72:D7:64:18:3E:6A:81:D6:64:87:BC:70:E9:B6:C5:9C:01:FE`

Windows software released before 2017-03-12 is signed with:

link:yubico-windows-code-2016.pem[]

SHA256 fingerprint:: `F0:45:D8:A2:54:37:97:B1:29:6F:32:A1:4F:6C:BC:C6:13:5F:79:C5:18:EF:25:6C:B0:7F:C7:FD:01:70:5C:EB`

Windows software released before 2016-03-12 is signed with:

link:yubico-windows-code-2015.pem[]

SHA256 fingerprint:: `1F:DA:33:2D:C3:DB:B7:DA:13:1B:BE:78:6E:2E:F9:2C:40:86:59:08:E5:C8:AA:1C:FC:F7:C6:5F:35:37:E3:7E`

Windows software released before 2015-03-12 is signed with:

link:yubico-windows-code-2014.pem[]

SHA256 fingerprint:: `DB:75:AF:B8:AF:DF:5C:DC:F9:70:1E:0E:FA:4C:44:97:ED:BE:0D:95:DB:8D:12:82:77:23:C6:6B:69:FE:3E:8B`


=== Mac Software Signing

Our Mac executables are signed with a Yubico code signing certificate,
issued by Apple.

link:yubico-mac-code.pem[]

SHA256 fingerprint:: `3C:3F:C5:78:DE:63:8A:96:A3:73:61:BD:3F:9C:39:55:DA:69:08:CD:C9:AF:57:8D:41:02:74:95:98:B8:98:83`

Mac software released before 2017-09-25 is signed with:

link:yubico-mac-code-2012.pem[]

SHA256 fingerprint:: `F4:EC:6D:AF:9A:E6:AD:49:F6:D3:99:9A:D8:92:8E:A1:D3:A9:45:94:15:90:BC:33:BA:9D:8E:35:59:02:3C:BD`
