== YubiHSM 2 Setup Tool

The SDK ships with a tool called `yubihsm-setup` that helps with setting up a device for specific use cases.
The tool assumes familiarity with the key concepts of YubiHSM such as link:../../Concepts/Domain.adoc[Domains], link:../../Concepts/Capability.adoc[Capabilities] and link:../../Concepts/Object_ID.adoc[Object IDs]. It currently supports the following:

- setup for KSP/ADCS;
- restoring a previous configuration
- resetting the device to factory defaults
- exporting all existing objects

The tool is based around the concept of secret-sharing. When setting up Objects, those are exported with a freshly created Wrapkey. The key is never stored on disk, but rather it is printed on the screen as shares. The key concepts here are the number of shares, which is the number of parts the key should be divided into, and the security threshold, which is the minimum number of shares required to reconstruct the Wrapkey.

Besides splitting the Wrapkey into shares, the tool (by default) also exports under wrap all the newly created objects and saves them in the current directory. This can be used at a later time to "clone" or recover a device. This operation can be performed either with `yubihsm-setup` or manually if the wrapping key is known.

By default, the Authkey used to establish a Session with the device is also normally deleted by the various commands.

Default behavior can be altered with command-line options. For more information consult the tool's help.
