== PIV certificate slots
A PIV-enabled YubiKey holds 4 distinct slots for certificates, as specified in
the link:http://csrc.nist.gov/groups/SNS/piv/standards.html[PIV standards
document]. Each of these slots is capable of holding an X.509 certificate,
together with its accompanying private key. Technically these four slots are
very similar, but they are used for different purposes.

=== Slot 9a: PIV Authentication
This certificate and its associated private key is used to authenticate the
card and the cardholder. This slot is used for things like system login. The
end user PIN is required to perform any private key operations. Once the PIN
has been provided successfully, multiple private key operations may be
performed without additional cardholder consent.

=== Slot 9c: Digital Signature
This certificate and its associated private key is used for digital signatures
for the purpose of document signing, or signing files and executables. The end
user PIN is required to perform any private key operations. The PIN must be
submitted every time immediately before a sign operation, to ensure cardholder
participation for every digital signature generated.

=== Slot 9d: Key Management
This certificate and its associated private key is used for encryption for the
purpose of confidentiality. This slot is used for things like encrypting
e-mails or files. The end user PIN is required to perform any private key
operations. Once the PIN has been provided successfully, multiple private key
operations may be performed without additional cardholder consent.

=== Slot 9e: Card Authentication
This certificate and its associated private key is used to support additional
physical access applications, such as providing physical access to buildings
via PIV-enabled door locks. The end user PIN is NOT required to perform private
key operations for this slot.
