== Device setup
Before starting to use the PIV functionality of a YubiKey, it is important to
change the PIN, PUK and Management keys from their default values. See
link:../Introduction/Admin_access.html[Admin access] for details on what these
unlock. For typical usage, you will want to memorize the PIN, and keep a copy
of the PUK and Management keys in a secure location.

=== Prerequisites
* a PIV enabled YubiKey
* the link:/yubico-piv-tool[yubico-piv-tool] or link:/yubikey-manager-qt[YubiKey Manager] software

=== Using YubiKey Manager for device setup
YubiKey Manager allows you to change the PIN, PUK and Management Key.

    Applications > PIV > Configure PINs

The Management Key can be protected with the PIN, meaning that it's saved on
the device in a location only readable with the PIN. This lets the user access the
key management features while only having to remember the PIN.

The link:/yubikey-manager[YubiKey Manager CLI] can also be used for device setup.

  $ ykman piv change-pin
  $ ykman piv change-puk
  $ ykman piv change-management-key

It also allows you to generate a random management key and store it on the device,
protected with the PIN.

  $ ykman piv change-management-key --generate --protect

=== Using yubico-piv-tool for device setup
The Management Key is set by invoking the `set-mgm-key` action. You will need
to provide the currently set Management Key (using `--key`), and the new key to
set (using `--new-key`). If the default Management Key is currently set you may omit
the `--key` argument. Keys are provided as 24-byte hex strings, and should be
randomly generated.

  $ key=$(export LC_CTYPE=C; dd if=/dev/urandom 2>/dev/null | tr -d '[:lower:]' | tr -cd '[:xdigit:]' | fold -w48 | head -1)
  $ echo $key
  $ yubico-piv-tool -a set-mgm-key --new-key=$key --key=010203040506070801020304050607080102030405060708

Changing the PIN is done by invoking the `change-pin` action and providing the
current PIN (using the `-P` argument), and a new PIN to set (using `-N`).

  $ yubico-piv-tool -a change-pin -P 123456 -N <NEW PIN>

Changing the PUK is done by invoking the `change-puk` action and providing the
current PUK (using the `-P` argument), and a new PUK to set (using `-N`).

  $ yubico-piv-tool -a change-puk -P 12345678 -N <NEW PUK>

=== Recovering from a blocked PIN
If the wrong PIN is entered 3 times consecutively, the PIN will become blocked.
Once blocked, the PIN cannot be used. To recover from this state you can
provide the PUK to set a new PIN, which will then not be blocked.

With YubiKey Manager this can be done by pressing the `Unblock PIN` button found
under `Configure PINs`, or with the CLI.

  $ ykman piv unblock-pin

To set a new PIN using yubico-piv-tool you invoke the `unblock-pin` action and
provide the PUK (using `-P`) and a new PIN to set (using `-N`).

  $ yubico-piv-tool -a unblock-pin -P 12345678 -N <NEW PIN>

=== Recovering from a lost Management Key
If you've lost your Management Key the only way to recover is to completely
reset the PIV functionality, which will erase any keys or certificates stored
on the device and set the default PIN, PUK and Management Key. This will only
affect the PIV portion of your YubiKey, so any non-PIV configuration will
remain intact.

With YubiKey Manager this is done by pressing the `Reset PIV` button in the GUI,
or with the CLI.

  $ ykman piv reset

To reset PIV on your YubiKey using yubico-piv-manager you invoke the `reset`
action. Resetting the PIV functionality with yubico-piv-tool is only possibly
when both the PIN and PUK have been blocked. To ensure that both the PIN and
PUK are in a blocked state, you can run the following commands:

  # Attempt to use an invalid PIN multiple times to block it #
  $ yubico-piv-tool -a verify-pin -P 000000
  $ yubico-piv-tool -a verify-pin -P 000000
  $ yubico-piv-tool -a verify-pin -P 000000
  $ yubico-piv-tool -a verify-pin -P 000000

  # Attempt to change PUK using an invalid PUK multiple times to block it #
  $ yubico-piv-tool -a change-puk -P 000000 -N 000001
  $ yubico-piv-tool -a change-puk -P 000000 -N 000001
  $ yubico-piv-tool -a change-puk -P 000000 -N 000001
  $ yubico-piv-tool -a change-puk -P 000000 -N 000001

Once PIN and PUK are both blocked, you can reset the YubiKey.

  $ yubico-piv-tool -a reset
