== Securing SSH with OpenPGP or PIV
Securing communication with remote systems via SSH can be done by using key-based authentication with the user’s key
residing on a physical YubiKey. With a YubiKey, the user’s SSH key data can be secured using OpenPGP and/or PIV.
Typically, deployment considerations or the particular use case will dictate which application to use.

If you use the OpenPGP option for SSH, the same key will be used for both authentication and signing. This is
demonstrated by Git, which uses GnuPG, that uses the same key to grant access to a repository via SSH and to sign a
commit. However, the OpenPGP option is more complicated to set up properly since the SSH communication is done through
the GnuPG agent. The PIV option, on the other hand, would probably be easier for anyone who does not have a reason to
use the same key for authentication and signing. Furthermore, for the PIV option, you can use the opensc-pkcs11 module,
or our own ykcs11 module. Our ykcs11 module is a lighter software package, so it would probably offer an easier path
for someone who does not already have the OpenSC software installed. The same goes for OpenPGP vs PIV as well, if you
already have GnuPG working.


For a developer who uses Git to sign his/her commits, the OpenPGP path is typically the natural one, because GnuPG
needs to be working to enable the use of Git signatures. With OpenPGP, it is only necessary to upload a single public
key, which Git then uses both to authenticate an SSH connection (used when accessing the specific repository, for
example when pushing one’s commits) and for verifying the signatures on Git commits.

=== OpenPGP
OpenPGP keys are managed on the OpenPGP function of the YubiKey. OpenPGP for SSH supports a more direct flow between
the user and their key management, making it ideal for independent or open source developers who want to ensure they
maintain control over their SSH keys.

Instructions for setting up SSH with OpenPGP and the YubiKey are available here:
link:../../PGP/SSH_authentication/index.adoc[SSH Authentication]

==== Advantages to OpenPGP
OpenPGP makes it simple to manage keys on a single local machine controlled by the user. Using the OpenPGP software,
users have complete control over the details of a certificate, including the key algorithm size and type, expiration
date, associated user information and other details. The private key remains completely in the user’s control, existing
only on the machine used to generate it and/or on the secure element of the YubiKey itself.

Furthermore, OpenPGP makes it simple to share the corresponding public key, allowing for usage of the OpenPGP key
beyond just SSH. A popular usage is to have the same key for authenticating into an SSH session, for Git code signing
and for email encryption. Since OpenPGP has cross-platform support on Windows, Linux and MacOS, an OpenPGP key on a
YubiKey can also enable SSH authentication across all platforms as well.

==== Considerations when using OpenPGP
As powerful as OpenPGP is, there are some drawbacks which need to be kept in mind. One of the great strengths of
OpenPGP—the direct generation of a key on a local machine—can lead to loss of access if the YubiKey holding the
OpenPGP key becomes unavailable. This can be mitigated if the private key is securely backed up.

In larger organizations, OpenPGP’s ability to run without a greater framework also can hinder the uniform application
of security policies. Without a central authority enforcing a standard set of attributes during key generation, there
is a risk of a user unintentionally generating a weak key or setting an expiration date too far in the future or too
soon. Again, this can be offset via training and documentation, but this mitigation strategy assumes users read the
documentation.

While OpenPGP is widely used for signing and encryption services, it is not commonly used for centrally managed
authentication. When using certificate-based authentication, the lack of a framework to support a credential authority
means OpenPGP is not supported. This and the fact that OpenPGP on a smart card YubiKey is limited to a single master
key (split into 3 sub-keys), credential management services and certificate authorities have not added native support
for OpenPGP credentials.

=== PIV
OpenSSH is one of the most widely used utilities suite based on the SSH protocol, which provides a secure channel
over an unsecured network in a client-server architecture. The YubiKey stores and manages RSA and EC asymmetric keys
within the PIV application, enabling authentication to a server through OpenSSH using the public key authentication
method and the PKCS#11 interface. This method can be widely utilized in large enterprises or corporate solutions for
credential management.

Instructions for setting up SSH with PIV and the YubiKey are available here:
link:SSH_user_certificates.adoc[SSH User Certificates].

==== Advantages to PIV
Using PIV for SSH enables the primary strengths of a centrally managed PKI framework to be extended to secure remote
access. As the keys can be issued from a central location, managed account recovery can be supported in the event a
YubiKey is unavailable. In addition, the centralized management of generated keys permits the standardized enforcement
of security policies across an organization. Many machine-based authentication methods use asymmetric keys - extending
them to a YubiKey allows for all of the advantages to be maintained while also adding an additional layer of security.

As the PIV application on the YubiKey allows for multiple keys to be loaded and used, the SSH use case may be added
to existing functions already supported on a YubiKey, such as Windows Login or network access. Furthermore, as PKCS#11
interface is widely supported, there are many options for managing asymmetric keys on a YubiKey. A large organization
can take advantage of the features PIV offers to create a process-driven, uniform and well-documented YubiKey
implementation of secure access.

==== Considerations when using PIV
While PIV offers a number of advantages in regards to the management of credentials used to secure a connection,
there are challenges to constructing such a solution. Primary among these challenges is the lack of chain validation.
Unlike the case with X.509 certificates where a certificate chain is used to verify the authenticity of a key, with
OpenSSH public key authentication method, each individual public key needs to be imported into the server and marked
as an authorized key. Revoked keys are also marked individually to deny them further access.
