= Passkey for developers overview
:description: Begin your passkey implementation journey
:keywords: passkey, passkeys, developer, high assurance, FIDO2, CTAP, WebAuthn

Begin your passkey implementation journey

Passkeys are the long awaited replacement for passwords. While passwords have been the primary standard in securing user accounts, they are not without issues. Passwords are easy to forget, and easily phishable; which has led to security breaches in various industries such as energy, healthcare, and technology. 

For years Yubico has been contributing to the WebAuthn standard, which is the protocol that enables secure authentication using passkeys. Yubico’s contribution, along with recent announcements from other major technology companies, have brought passkeys into the mainstream; leading to a future where a large adoption by consumer and enterprise users is possible. 

What does this mean for your application, and your users? As adoption continues to increase, your users will expect that your application allows them to leverage their passkey supported devices to securely and seamlessly authenticate into their accounts. 

Whether you are working on an identity provider, a widely used consumer app, or on enterprise service, this guide will provide all the necessary technical knowledge required to adopt passkeys into your application. 

link:/passkeys/Quick_overview_of_WebAuthn_FIDO2_and_CTAP.html[Click continue to begin your passkey journey]
