= Passkey workshop
:description: Begin your passkey implementation journey
:keywords: passkey, passkeys, developer, high assurance, FIDO2, CTAP, WebAuthn

All things passkey development

Passkeys are the long awaited replacement for passwords. While passwords have been the primary standard in securing user accounts, they are not without issues. Passwords are easy to forget, and easily phishable; which has led to security breaches in various industries such as energy, healthcare, and technology.

For years Yubico has been contributing to the WebAuthn standard, which is the protocol that enables secure authentication using passkeys. Yubico’s contribution, along with recent announcements from other major technology companies, have brought passkeys into the mainstream; leading to a future where a large adoption by consumer and enterprise users is possible.

What does this mean for your application, and your users? As adoption continues to increase, your users will expect that your application allows them to leverage their passkey supported devices to securely and seamlessly authenticate into their accounts.

In this workshop, we will walk through a full end-to-end passkey enabled application. Whether you are working on an identity provider, a widely used consumer app, or on enterprise service, you should be able to walk away from this material knowing the fundamentals of passkeys, and how to showcase the art-of-the-possible for your use case.

++++
<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/9bv2Q4fQfp4" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
++++

Click the link below to begin your passkey journey!

link:https://yubicolabs.github.io/passkey-workshop/[Link to Yubico's passkey workshop]

