== DEVICE INFO

Get device metadata.

== Description

Gets device version, device serial, supported Algorithms and available log entries.

== Shell example

Fetch device info for currently connected device:

  yubihsm> get deviceinfo
  Version number:         2.0.0
  Serial number:          2000000
  Log used:               2/62
  Supported algorithms:   rsa-pkcs1-sha1, rsa-pkcs1-sha256, rsa-pkcs1-sha384,
                          rsa-pkcs1-sha512, rsa-pss-sha1, rsa-pss-sha256,
                          rsa-pss-sha384, rsa-pss-sha512, rsa2048,
                          rsa3072, rsa4096, ecp256,
                          ecp384, ecp521, eck256,
                          ecbp256, ecbp384, ecbp512,
                          hmac-sha1, hmac-sha256, hmac-sha384,
                          hmac-sha512, ecdsa-sha1, ecdh,
                          rsa-oaep-sha1, rsa-oaep-sha256, rsa-oaep-sha384,
                          rsa-oaep-sha512, aes128-ccm-wrap, opaque,
                          x509-cert, mgf1-sha1, mgf1-sha256,
                          mgf1-sha384, mgf1-sha512, template-ssh,
                          yubico-otp-aes128, yubico-aes-auth, yubico-otp-aes192,
                          yubico-otp-aes256, aes192-ccm-wrap, aes256-ccm-wrap,
                          ecdsa-sha256, ecdsa-sha384, ecdsa-sha512,
                          ed25519, ecp224,

== Protocol details

=== Command

|===========
|T~c~ = 0x06
|L~c~ = 0
|V~c~ = Ø
|===========

=== Response

|=========================================================
|T~r~ = 0x86
|L~r~ = 9 + algorithms
|V~r~ = V~Major~ \|\| V~Minor~ \|\| V~Build~ \|\| S \|\| L~total~ \|\| L~used~ \|\| A
|=========================================================

V~Major~ := Major version number

V~Minor~ := Minor version number

V~Build~ := Build version number

S := Serial number (4 bytes)

L~total~ := Log Store size expressed in number of log entries

L~used~ := Log lines used

A := List of supported link:../Concepts/Algorithms.adoc[Algorithms]
