== GENERATE SYMMETRIC KEY

Available with firmware version 2.3.1 or later.

Generate a symmetric key.

== Description

Generate a symmetric Key in the device.

== Shell Example

Generate a new AES256 key in the device:

  yubihsm> generate symmetric 0 0 aeskey 1 encrypt-ecb,decrypt-ecb aes256
  Generated symmetric key 0xc040

== Protocol Details

=== Command

|=======================
|T~c~ = 0x6e
|L~c~ = 2 + 40 + 2 + 8 + 1
|V~c~ = I \|\| L \|\| D \|\| C \|\| A
|=======================

Generate a symmetric key with a given ID. Each parameter has a
fixed length and the order is compulsory.

I := link:../Concepts/Object_ID.adoc[Object ID] of the symmetric key (2 bytes)

L := link:../Concepts/Label.adoc[Label] (40 bytes)

D := link:../Concepts/Domain.adoc[Domains] (2 bytes)

C := link:../Concepts/Capability.adoc[Capabilities] (8 bytes)

A := link:../Concepts/Algorithms.adoc[Algorithm] (1 byte)

=== Response

|===========
|T~r~ = 0xee
|L~r~ = 2
|V~r~ = I
|===========

I := link:../Concepts/Object_ID.adoc[Object ID] of the created symmetric key (2 bytes)
