== GENERATE WRAP KEY

Generate a Wrap Key.

== Description

Generate a Wrap Key that can be used for export, import, wrap data and unwrap
data.

== Shell Example

Generate a new Wrap Key that can be used for wrap and unwrap:

  yubihsm> generate wrapkey 0 0 wrapkey 1 wrap-data:unwrap-data none aes256-ccm-wrap
  Generated Wrap key 0x5b3a

== Protocol Details

=== Command

|======================
|T~c~ = 0x5b
|L~c~ = 2 + 40 + 2 + 8 + 1 + 8
|V~c~ = I \|\| L \|\| D \|\| C \|\| A \|\| DC
|======================

I := link:../Concepts/Object_ID.adoc[Object ID] of the Wrap Key (2 bytes)

L := link:../Concepts/Label.adoc[Label] (40 bytes)

D := link:../Concepts/Domain.adoc[Domains] (2 bytes)

C := link:../Concepts/Capability.adoc[Capabilities] (8 bytes)

A := link:../Concepts/Algorithms.adoc[Algorithm] (1 byte)

DC := Delegated link:../Concepts/Capability.adoc[Capabilities] (8 bytes)

=== Response

|===========
|T~r~ = 0xdb
|L~r~ = 2
|V~r~ = I
|===========

I := link:../Concepts/Object_ID.adoc[Object ID] of created Wrap Key (2 bytes)
