== GET OBJECT INFO

Get object metadata.

== Description

Fetch all metadata about an object.

== Shell example

Get object info for asymmetric key with id 0x1e15:

  yubihsm> get objectinfo 0 0x1e15 asymmetric
  id: 0x1e15, type: asymmetric, algorithm: rsa2048, label: "rsakey", length: 896, domains: 1, sequence: 0, origin: imported, capabilities: asymmetric_sign_pkcs

== Protocol details

=== Command

|===============
|T~c~ = 0x4e
|L~c~ = 2 + 1
|V~c~ = I \|\| T
|===============

I := Object ID (2 bytes)

T := link:../Concepts/Object.html[Type] (1 byte)

=== Response

|==================================================
|T~r~ = 0xce
|L~r~ = 8 + 2 + 2 + 2 + 1 + 1 + 1 + 1 + 40 + 8
|V~r~ = C \|\| I \|\| l \|\| D \|\| T \|\| A \|\| S \|\| O \|\| L \|\| DC
|==================================================

C := link:../Concepts/Capability.html[Capabilities] (8 bytes)

I := Object Id (2 bytes)

l := Object Length (2 bytes)

D := Domains (2 bytes)

T := link:../Concepts/Object.html[Type] (1 byte)

A := link:../Concepts/Algorithm.html[Algorithm] (1 byte)

S := Sequence (1 byte)

O := Origin (1 byte)

L := Label (40 bytes)

DC := Delegated link:../Concepts/Capability.html[Capabilities] (8 bytes)
