== IMPORT WRAPPED

Import an wrapped/encrypted object into the device.

== Description

Import a wrapped/encrypted Object that was previously exported by an YubiHSM 2 
device. The imported object will retain its metadata (Object ID, Domains, 
Capabilities ...etc), however, the object's origin will be marked as 'imported'
 instead of 'generated' 

== Shell Example

Import the Object stored in `key.enc` and unwrap it using Wrap Key `0xcf94`

  yubihsm> put wrapped 0 0xcf94 key.enc
  Object imported as 0x997e of type asymmetric

== Protocol Details

=== Command

|======================
|T~c~ = 0x4b
|L~c~ = 2 + 13 + L~O~
|V~c~ = I \|\| N \|\| O
|======================

I := link:../Concepts/Object_ID.adoc[Object ID] of the Wrap Key (2 bytes)

N := Nonce associated with this wrapped Object (13 bytes)

O := Wrapped link:../Concepts/Object.adoc[Object] (Length dependent on Object)

=== Response

|===============
|T~c~ = 0xcb
|L~c~ = 3
|V~c~ = T \|\| I
|===============

T := link:../Concepts/Object.adoc[Type] of imported Object (1 byte)

I := link:../Concepts/Object_ID.adoc[Object ID] of imported Object (2 bytes)
