== LIST OBJECTS

List Objects in device.

== Description

Get a filtered list of link:../Concepts/Object.adoc[Objects] from the device.

== Shell Example

Get a list of all Asymmetric Keys for Session `0`:

  yubihsm> list objects 0 0 asymmetric-key
  Found 4 object(s)
  id: 0x3479, type: asymmetric-key, sequence: 0
  id: 0x7df6, type: asymmetric-key, sequence: 0
  id: 0x9602, type: asymmetric-key, sequence: 0
  id: 0xd6cd, type: asymmetric-key, sequence: 0

== Protocol Details

=== Command

|===============
|T~c~ = 0x48
|L~c~ = L~F~
|V~c~ = F
|===============

F := List of Tag-Value pairs describing a filter to apply. Possible tags to
use for filtering are described in the table below.

[options="header"]
|==========================
|Name | Identifier | Length
|link:../Concepts/Object_ID.adoc[ID] | 0x01 | 2 bytes
|link:../Concepts/Object.adoc[TYPE] | 0x02 | 1 byte
|link:../Concepts/Domain.adoc[DOMAINS] | 0x03 | 2 bytes
|link:../Concepts/Capability.adoc[CAPABILITIES] | 0x04 | 8 bytes
|link:../Concepts/Algorithms.adoc[ALGORITHM] | 0x05 | 1 byte
|link:../Concepts/Label.adoc[LABEL] | 0x06 | 40 bytes
|==========================

=== Response

|===============
|T~r~ = 0xc8
|L~r~ = 4 * N
|V~r~ = R~1~ \|\| R~2~ \|\| … \|\| R~N~
|===============

R~i~ := link:../Concepts/Object_ID.adoc[Object ID] (2 bytes), link:../Concepts/Object.adoc[Type] (1 byte) and link:../Concepts/Sequence.adoc[Sequence] (1 byte).
