== LIST OBJECTS

List objects in device.

== Description

Get a filtered list of objects from the device.

== Shell example

Get a list of all acessible objects for session 0:

  yubihsm> list objects 0 
  Found 6 object(s)
  id: 0x0001, type: authkey, sequence: 0
  id: 0xe255, type: opaque, sequence: 0
  id: 0xba8d, type: opaque, sequence: 0
  id: 0xbb72, type: authkey, sequence: 0
  id: 0x1e15, type: asymmetric, sequence: 0
  id: 0x2846, type: asymmetric, sequence: 0

== Protocol details

=== Command

|===============
|T~c~ = 0x48
|L~c~ = L~F~
|V~c~ = F
|===============

F := List of Tag - Value pairs describing a filter to apply. Possible tags to
use for filtering are described in the table below.

[options="header"]
|==========================
|Name | Identifier | Length

|ID | 0x01 | 2
|link:../Concepts/Object.html[TYPE] | 0x02 | 1
|DOMAINS | 0x03 | 2
|link:../Concepts/Capability.html[CAPABILITIES] | 0x04 | 8
|link:../Concepts/Algorithm.html[ALGORITHM] | 0x05 | 1
|LABEL | 0x06 | 40
|==========================

=== Response

|===============
|T~r~ = 0xc8
|L~r~ = L~R~
|V~r~ = R
|===============

R := List of object id, type and sequence, 4 bytes per object.
