== PUT SYMMETRIC KEY

Available with firmware version 2.3.1 or later.

Import a symmetric Key.

== Description

Import a symmetric Key into the device.

== Shell Example

Store an AES128 into the device:

  yubihsm> put symmetric 0 0 aeskey 1 encrypt-cbc,decrypt-cbc aes128 0a8a7ecc862b3d42b5dc127c111da0f4
  Stored symmetric key 0x71c9

== Protocol Details

=== Command

|=================================================
|T~c~ = 0x6d
|L~c~ = 2 + 40 + 2 + 8 + 1 + L~K~
|V~c~ = I \|\| L \|\| D \|\| C \|\| A \|\| K
|=================================================

The key parameters vary according to the chosen algorithm. Each parameter has
a fixed length and the order is compulsory.

I := link:../Concepts/Object_ID.adoc[Object ID] of the symmetric key (2 bytes)

L := link:../Concepts/Label.adoc[Label] (40 bytes)

D := link:../Concepts/Domain.adoc[Domains] (2 bytes)

C := link:../Concepts/Capability.adoc[Capabilities] (8 bytes)

A := link:../Concepts/Algorithms.adoc[Algorithm] (1 byte)

K := Key integer (16, 24 or 32 bytes)

=== Response

|===========
|T~r~ = 0xed
|L~r~ = 2
|V~r~ = I
|===========

I := ID of created Object (2 bytes)
