== PUT AUTHKEY

Store a new Authkey.

== Description

Store an Authkey in the device.

== Shell Example

Store a new Authkey derived from the password `newpassword`:

  yubihsm> put authkey 0 0 authkey 1 asymmetric_gen,asymmetric_sign_pkcs asymmetric_sign_pkcs newpassword
  Stored Authentication key 0xbb72

== Protocol Details

=== Command

|==========================================
|T~c~ = 0x44
|L~c~ = 2 + 40 + 2 + 8 + 1 + 8 + 16 + 16
|V~c~ = K \|\| L \|\| D \|\| C \|\| A \|\| d \|\| K~e~ \|\| K~m~
|==========================================

K := link:../Concepts/Object_ID.adoc[Key ID] (2 bytes)

L := link:../Concepts/Label.adoc[Label] (40 bytes)

D := link:../Concepts/Domain.adoc[Domains] (2 bytes)

C := link:../Concepts/Capability.adoc[Capabilities] (8 bytes)

A := link:../Concepts/Algorithms.adoc[Algorithm] (1 bytes)

d := Delegated link:../Concepts/Capability.adoc[Capabilities] (8 bytes)

K~e~ := Encryption Key (16 bytes)

K~m~ := Mac Key (16 bytes)

=== Response

|===========
|T~r~ = 0xc4
|L~r~ = 2
|V~r~ = I
|===========

I := link:../Concepts/Object_ID.adoc[ID] of created Object (2 bytes)
