== PUT AUTHENTICATION KEY

Store a new Authentication Key.

== Description

Store an Authentication Key in the device.

== Shell Example

Store a new Authentication Key derived from the password `newpassword`:

  yubihsm> put authkey 0 0 authkey 1 generate-asymmetric-key,sign-pkcs sign-pkcs newpassword
  Stored Authentication key 0xbb72

== Protocol Details

=== Command

|==========================================
|T~c~ = 0x44
|L~c~ = 2 + 40 + 2 + 8 + 1 + 8 + 16 + 16
|V~c~ = I \|\| L \|\| D \|\| C \|\| A \|\| DC \|\| K~e~ \|\| K~m~
|==========================================

I := link:../Concepts/Object_ID.adoc[Object ID] of the Authentication Key (2 bytes)

L := link:../Concepts/Label.adoc[Label] (40 bytes)

D := link:../Concepts/Domain.adoc[Domains] (2 bytes)

C := link:../Concepts/Capability.adoc[Capabilities] (8 bytes)

A := link:../Concepts/Algorithms.adoc[Algorithm] (1 bytes)

DC := Delegated link:../Concepts/Capability.adoc[Capabilities] (8 bytes)

K~e~ := Encryption Key (16 bytes)

K~m~ := Mac Key (16 bytes)

=== Response

|===========
|T~r~ = 0xc4
|L~r~ = 2
|V~r~ = I
|===========

I := link:../Concepts/Object_ID.adoc[Object ID] of created Authentication Key (2 bytes)
