== PUT ASYMMETRIC KEY

Import an Asymmetric Key.

== Description

Import an Asymmetric Key into the device.

== Shell Example

Store an RSA key from `key.pem` into the device:

  yubihsm> put asymmetric 0 0 rsakey 1 sign-pkcs key.pem
  Stored Asymmetric key 0x1e15

== Protocol Details

=== Command

|=================================================
|T~c~ = 0x45
|L~c~ = 2 + 40 + 2 + 8 + 1 + L~P1~ { + L~P2~ }
|V~c~ = I \|\| L \|\| D \|\| C \|\| A \|\| P~1~ { \|\| P~2~ }
|=================================================

The key parameters vary according to the chosen algorithm. Each parameter has
a fixed length and the order is compulsory.

I := link:../Concepts/Object_ID.adoc[Object ID] of the Asymmetric Key (2 bytes)

L := link:../Concepts/Label.adoc[Label] (40 bytes)

D := link:../Concepts/Domain.adoc[Domains] (2 bytes)

C := link:../Concepts/Capability.adoc[Capabilities] (8 bytes)

A := link:../Concepts/Algorithms.adoc[Algorithm] (1 byte)

P~1~ :=

For RSA: secret prime p (128, 192 or 256 bytes) +
 +
For ECC: private key integer d (32, 48, 64 or 66 bytes) +
 +
For EDC: private key integer k (32 bytes)


P~2~ :=

For RSA: secret prime q (128, 192 or 256 bytes) +
 +
For ECC: NOT DEFINED +
 +
For EDC: NOT DEFINED +


=== Response

|===========
|T~r~ = 0xc5
|L~r~ = 2
|V~r~ = I
|===========

I := ID of created Object (2 bytes)
