== PUT TEMPLATE

Store a Template.

== Description

Stores a Template in the device. The size of the object is currently limited to what will fit into one message to the YubiHSM (2021 bytes, including the headers).

== Shell Example

Store the SSH Template in file `template.dat` in the device:

  yubihsm> put template 0 0 ssh_template 1 none template-ssh template.dat
  Stored Template object 0x7b19

== Protocol Details

=== Command

|=============================
|T~c~ = 0x5e
|L~c~ = 2 + 40 + 2 + 8 + 1 + L~D~
|V~c~ = I \|\| L \|\| D \|\| C \|\| A \|\| D
|=============================

I := link:../Concepts/Object_ID.adoc[Object ID] of the Template (2 bytes)

L := link:../Concepts/Label.adoc[Label] (40 bytes)

D := link:../Concepts/Domain.adoc[Domains] (2 bytes)

C := link:../Concepts/Capability.adoc[Capabilities] (8 bytes)

A := link:../Concepts/Algorithms.adoc[Algorithm] (1 byte)

D := Template data

=== Response

|===========
|T~r~ = 0xde
|L~r~ = 2
|V~r~ = I
|===========

I := link:../Concepts/Object_ID.adoc[Object ID] of created Template (2 bytes)
