== PUT ASYMMETRIC

Import an Asymmetric key.

== Description

Import an Asymmetric key into the device.

== Shell Example

Store an RSA key from key.pem into the device:

  yubihsm> put asymmetric 0 0 rsakey 1 asymmetric_sign_pkcs key.pem
  Stored Asymmetric key 0x1e15

== Protocol Details

=== Command

|=================================================
|T~c~ = 0x45
|L~c~ = 2 + 40 + 2 + 8 + 1 + L~P1~ { + L~P2~ }
|V~c~ = K \|\| L \|\| D \|\| C \|\| A \|\| P~1~ { \|\| P~2~ }
|=================================================

The key parameters vary according to the chosen algorithm. Each parameter has
a fixed length and the order is compulsory.

K := link:../Concepts/Object_ID.adoc[Key ID] (2 bytes)

L := link:../Concepts/Label.adoc[Label] (40 bytes)

D := link:../Concepts/Domain.adoc[Domains] (2 bytes)

C := link:../Concepts/Capability.adoc[Capabilities] (8 bytes)

A := link:../Concepts/Algorithms.adoc[Algorithm] (1 byte)

P~1~ :=

For RSA: secret prime p (0x0080 | 0x00C0 | 0x0100 bytes) +
 +
For ECC: private key integer d (0x0020 | 0x0030 | 0x0040 | 0x0042 bytes) +
 +
For EDC: private key integer k (0x0020 bytes)


P~2~ :=

For RSA: secret prime q (0x0080 | 0x00C0 | 0x0100 bytes) +
 +
For ECC: NOT DEFINED +
 +
For EDC: NOT DEFINED +


=== Response

|===========
|T~r~ = 0xc5
|L~r~ = 2
|V~r~ = I
|===========

I := ID of created Object (2 bytes)
