== SET OPTION

Set a device-global option.

== Description

Set device-global options that affect general behavior. Each invocation
of this command sets a single option, which is represented as a
TAG-LENGTH-VALUE (TLV).

== Shell Example

Turn off audit logging for Sign HMAC (command `53`) and Verify HMAC (command `5c`):

  yubihsm> put option 0 command_audit 53005c00

== Protocol Details

=== Command

|===============
|T~c~ = 0x4f
|L~c~ = 3 + L~o~
|V~c~ = T~O~
|===============

T~o~ := The TLV encoding of the selected option

L~o~ := The option-specific length in bytes

The options currently supported are the following:

TAG is 1 byte

LENGTH is 2 bytes

VALUE is L~o~ bytes

Tags:
|===
|Force audit | 0x01
|Command audit | 0x03
|===

Values:
|===
|OFF | 0x00 | Disabled
|ON  | 0x01 | Enabled
|FIX | 0x02 | Enabled, not possible to turn off
|===

There are two supported options, `Force audit` and `Command audit`.

With `Force audit` set, the device will refuse operations as long as
the link:../Concepts/Logs.adoc[Log Store] is full. It takes a `1` byte
value option.

`Command audit` can be used to toggle whether a specific
command should be logged, this takes tuples of command number and option
value.

=== Response

|===========
|T~r~ = 0xcf
|L~r~ = 0
|V~r~ = Ø
|===========
