== SIGN PKCS1

Sign with RSA-PKCS#1v1.5.

== Description

Computes a digital signature using RSA-PKCS1v1.5 on the provided data.

== Shell Example

Sign the data in the file `test` using rsa-pkcs1-sha256:

  yubihsm> sign pkcs1v1_5 0 0x1e15 rsa-pkcs1-sha256 test
  eu9HQceSs0zsUogVloovRRcDGtkBj5AIp2Nnk6LWT4KbQZX8ac+vmFtVotjDIF9PkQ9MA8KlsfUGvXAxpnvUyin3BjGvzENu5XRi+ZOGP4m8777zbDi1v7FKQSx8/KdZf4tulIsL4rM4M+uH/QoQ83vWty4c63QjcSlZJQDsdHn9r3E5or3QgBo06yK2Rd8W3WYGloSPvDaGu7L87CDFyMniAQB//Sw7bYr4hbVpKIWi6q4VPhBKdaB6+FzTmYrqsSv1vwek0V4LbvyelTHlh9PpFuSFZeGJ/i1gkIeSO2XlKNLa4+AO+H+TYUOP3b6Qlhs3f7e4AFFWKE6lPpDHJA==

== Protocol Details

=== Command

|===============
|T~c~ = 0x047
|L~c~ = 2 + L~D~
|V~c~ = I \|\| D
|===============

I := link:../Concepts/Object_ID.adoc[Object ID] of the Asymmetric Key (2 bytes)

D := Digest

The Digest can be either a raw hash of data, where DigestInfo will be applied
in the device, or DigestInfo + hash. Hashes supported are SHA-1, SHA-256,
SHA-384 and SHA-512.

=== Response

|============
|T~r~ = 0xc7
|L~r~ = L~DS~
|V~r~ = DS
|============

DS := Resulting signature
