== Getting Started with Android

Native support for WebAuthn and FIDO is finally here for Android. Yubico provides a comprehensive library for developers to interact with YubiKeys from their Android applications. 

If you run into any issues during the development process, please fill out a developer https://support.yubico.com/support/tickets/new[support ticket] and our team will be happy to assist you.

=== Yubico Android SDK

* https://github.com/Yubico/yubikit-android[Download Android SDK]

The Yubico Android SDK (YubiKit for Android) is a library provided by Yubico to interact with YubiKeys. The library supports NFC-enabled and USB YubiKeys.

*YubiKit* is multi-module library with the following components:

https://github.com/Yubico/yubikit-android/blob/master/yubikit/README.md[YubiKit] - Provides functionality to detect YubiKey plugged in or tapped over NFC

https://github.com/Yubico/yubikit-android/blob/master/oath/README.md[OATH] - Allows applications,such as an authenticator app, to store OATH TOTP and HOTP secrets on a YubiKey, and to retrieve one-time passwords

https://github.com/Yubico/yubikit-android/blob/master/otp/README.md[OTP] - Provides classes to obtain Yubikey OTP

https://developers.google.com/identity/fido/android/native-apps[FIDO2] - Supports a subset of FIDO2

https://github.com/Yubico/yubikit-android/blob/master/piv/README.md[PIV] - Provides implementation of Personal Identity Verification (PIV)

https://github.com/Yubico/yubikit-android/blob/master/management/README.md[MGMT] - Provides subset of API for personal customization of YubiKey and HMAC-SHA1 challenge-response

All YubiKit modules has javadoc and sources deployed with the library archive. Use this documentation for a more detailed explanation of all the methods, properties and parameters from the API.

This library also comes with a Kotlin demo application https://github.com/Yubico/yubikit-android/tree/master/YubikitDemo[Yubikit Demo App]. 
