== Getting Started with Android

Yubico offers two great user experiences on Android employing a simple tap for NFC or a physical connection with USB.

*Authentication via NFC* is supported by the link:https://www.yubico.com/product/yubikey-5-nfc[YubiKey 5 NFC].

*Authentication via physical connection* is supported by the NFC keys named above and all of the other YubiKeys with the USB connector (see the link:https://support.yubico.com/support/solutions/articles/15000006476-yubikey-support-on-android[YubiKey support on Android article] for a list of these.



=== Yubico Android SDK

Yubico Android SDK (YubiKit for Android) is an Android library provided by Yubico to enable interaction between YubiKeys and Android devices. The library supports NFC-enabled and USB YubiKeys.

Documentation for the SDK, such as instructions on adding it to your project and getting started, is available
link:https://github.com/Yubico/yubikit-android[on GitHub].

JavaDoc APIs for the various modules can be found link:/yubikit-android/JavaDoc/[here].

=== Get Started

1. Pick up a link:https://www.yubico.com/products/compare-products-series/[YubiKey or a Security Key by Yubico].

2. Use the link:https://github.com/Yubico/yubikit-android/tree/main/AndroidDemo[YubiKit Demo App] to learn how to integrate the YubiKit for Android with your app.

3. Instructions for integrating and using the library are in the link:https://github.com/Yubico/yubikit-android#readme[README file] in the root folder of the yubikit-android page on GitHub.

If you run into any issues during the development process, please fill out a developer https://support.yubico.com/support/tickets/new[support ticket] and our team will be happy to assist you.
