== Getting Started with Android

Our new Android SDK provides native support for WebAuthn. Yubico offers two great user experiences on Android using a simple tap or a physical connection.

*Authentication via NFC* is supported by the link:https://www.yubico.com/product/yubikey-5-nfc[YubiKey 5 NFC] and by the link:https://www.yubico.com/product/security-key-nfc-by-yubico[Security Key NFC by Yubico].

*Authentication via physical connection* is supported by the NFC keys named above and all of the other YubiKeys and Security Keys with the USB connector (see link:https://support.yubico.com/support/solutions/articles/15000006476-yubikey-support-on-android[the YubiKey support on Android article] for a list of these.

Yubico provides a comprehensive library for developers to interact with YubiKeys from their Android applications.



=== Yubico Android SDK

The Yubico Android SDK (YubiKit for Android) is an Android library provided by Yubico to interact with YubiKeys on Android devices.

* https://github.com/Yubico/yubikit-android[Download Android SDK]

This multi-module library provides link:https://github.com/Yubico/yubikit-android/blob/master/yubikit/README.md[functionality to detect whether the YubiKey is plugged in or connected over NFC]. The APIs interact with the following features of NFC-enabled and USB YubiKeys:

* link:https://github.com/Yubico/yubikit-android/blob/master/oath/README.md[OATH] - Allows applications such as an authenticator app to store link:https://developers.yubico.com/OATH/[OATH TOTP and HOTP secrets] on a YubiKey and generate one-time passwords.

* link:https://github.com/Yubico/yubikit-android/blob/master/otp/README.md[OTP] - Provides implementation classes to obtain link:https://developers.yubico.com/OTP/[Yubico OTP] via USB or NFC.

* link:https://github.com/Yubico/yubikit-android/blob/master/piv/README.md[PIV] - Provides an implementation of the Personal Identity Verification (link:https://developers.yubico.com/PIV/[PIV]) interface.

* link:https://github.com/Yubico/yubikit-android/blob/master/management/README.md[MGMT] - Provides YubiKey management functionality, a subset of the API for personal customization of the YubiKey and the HMAC-SHA1 challenge-response.

In addition, the library provides a Kotlin demo application, the link:https://github.com/Yubico/yubikit-android/tree/master/YubikitDemo[YubiKit Demo App] which provides a complete example of how to integrate and use all the features of the library in an Android project.

[NOTE]
======
The pre-release version of the YubiKit Android SDK supported a subset of FIDO2. In this general availability version, the FIDO2 module has been removed. Because it wrapped the Google FIDO2 API provided by Google Play Services, its functionality was limited to that which was available from the underlying API. The current state of that API is so much improved that our own wrapper is no longer necessary.
======


=== Get Started

Pick up a link:https://www.yubico.com/products/compare-products-series/[YubiKey or a Security Key by Yubico].

Use the link:https://github.com/Yubico/yubikit-android/tree/master/YubikitDemo[YubiKit Demo App] to learn how to integrate the YubiKit for Android with your app.



If you run into any issues during the development process, please fill out a developer https://support.yubico.com/support/tickets/new[support ticket] and our team will be happy to assist you.
