= Securing Web Sites, Services and Applications
The internet is quickly evolving from its roots as a passive channel for displaying requested information to an interactive platform replacing traditional desktop OS’s for applications and services. However, a decentralized, cloud-based, universally accessible platform has its unique challenges to securing accounts and services. The YubiKey offers multiple solutions for adding multifactor authentication compatible with services of any type.

When choosing an option, it is important to understand all of the options available.

== FIDO2 / WebAuthn
The link:https://fidoalliance.org/[FIDO Alliance] has curated the new trails blazed by innovators in secure authentication, providing a standard, open platform for maintaining new specifications. WebAuthn represents a new way of performing authentication using public key cryptography, but without the overhead of a Public Key Infrastructure framework or a central trust authority.

FIDO protocols are ideal for web portals in which security is a top concern, and users can be reasonably expected to use a modern browser on a modern OS.

*Key Points:*

* Modern Protocol
* Public Key based
* Customer Self-Registration
* Privacy Protection
* Multiple implementation choices
* Immune to phishing
* Requires modern browser

link:https://developers.yubico.com/Developer_Program/Guides/Securing_Web_Services_with_WebAuthn.adoc[I want to use FIDO2 to secure my Web service]


== One-Time Passwords
OTPs (One-Time Passwords) have been the backbone of multifactor authentication for the vast majority of established system. We use OTPs from SMS messages, software apps like Google Authenticator or from authentication hardware, like YubiKeys. OTPs have a major advantage in that they are easy to implement user endpoints for - just include a text field to accept the typed input. While not as secure as the modern authentication protocols, OTPs, when implemented properly, provide security that only username and password cannot match.

OTPs are perfect for quickly standing up a multifactor authentication solution which will work across every environment.

*Key Points:*

* Universally Supported Protocol
* Very quick to enable
* Customer Self-Registration
* Multiple implementation choices
* Vulnerable to Phishing

link:https://developers.yubico.com/Developer_Program/Guides/Securing_Web_Services_with_OTP.adoc[I want to use OTPs to secure my Web service]


== Smart Cards
Smart cards provide a superior authentication solution, allowing for strong, centrally managed authentication which can be extended to secure OS endpoints as well. However, their strength relies on establishing a Public Key Infrastructure (PKI) framework which can be unwieldy to manage. However, should such a PKI deployment already be in place, say in a corporate or federal office, it can be leveraged to extend the same authentication to websites.

Smart Cards are perfect for extending an existing PKI deployment to securing web assets as well.

*Key Points:*

* Strong form of authentication
* Credentials are centrally managed - no user registration
* Credential lifecycle can be highly managed
* Immune to Phishing
* Requires a notable investment in a PKI framework
* Limited to members within an organization

link:https://developers.yubico.com/yubico-piv-tool/YKCS11/[I want to use Smart Cards to secure my Web service]
