== What is YubiKey OTP? ==
YubiKey +++<abbr title="One-Time Password">OTP</abbr>+++ is a simple yet strong authentication mechanism that
is supported by all YubiKeys out of the box. YubiKey OTP can be used as the second
factor in a 2-factor authentication scheme or on its own, providing 1-factor
authentication.

== API Key ==
Before you add YubiKey OTP to your application that uses YubiCloud (our network of validation servers) you
need to get an _API key_ from link:https://upgrade.yubico.com/getapikey/[here]. Getting an API key is quick and
free and helps us preventing misuse of YubiCloud.

== Implementing ==
We provide two alternatives:

 * *link:Plugins[Integration plugins]* for software such as Wordpress, phpBB and FreeRADIUS.
   This should be the easiest alternative if you are using supported software.
 * *link:Libraries[Libraries for programming languages]* used to create your own integration.

By default OTP validation is done against _YubiCloud_, Yubico's free-to-use
validation cloud; but you can also link:foo[host a validation server] yourself.

== Understanding ==
While not required, it can be interesting and useful to know how a YubiKey OTP is generated. This
is explained in link:OTPs_Explained.html[OTPs explained].

pass::[<script src="jquery-1.11.1.min.js"></script><script src="raphael-min.js"></script><script src="underscore-min.js"></script><script src="sequence-diagram-min.js"></script><script>$(".diagram").sequenceDiagram({theme: 'simple'});</script>]

