== Validating YubiKey OTPs using a library ==
YubiKey OTPs can be validated by _YubiCloud_ or a self-hosted validation server.
Throughout this document we will refer to both these alternatives simply as _YubiCloud_.

This sequence diagram descibes a typical YubiKey OTP implementation:

++++
<div class="diagram">
Browser->Server: OTP (and username\n& password)
Note over Server: verify username\nand password
Server->YubiCloud: OTP
YubiCloud-->Server: response
</div>
++++

By using a library, you abstract away the communication with the YubiCloud:

++++
<div class="diagram">
Browser->Server: OTP (and username\n& password)
Note over Server: verify username\nand password
Note over Server: ask library to\nvalidate OTP
</div>
++++

For example, _ask library to validate OTP_ would be implemented like this in Java:

[source, java]
----
// otp is the OTP from the Yubikey
otp_is_valid = client.verify(otp)
----

After validating the OTP, you also want to make sure that the YubiKey belongs to the user logging in.
This is done by comparing the first 12 characters of the OTP (which is the YubiKey's ID) with the
YubiKey ID that is associated with the user:

[source, java]
yubikey_belongs_to_user = otp[:12] == user.yubikey_id

=== Client-side ===
The client-side (browser-side) is not handled by libraries. Luckily, it is really easy – 
just add another text field to your existing login form. From a user point of view, _press Enter_ is replaced with _touch the YubiKey button_.

== Available libraries ==
=== By Yubico ===

[options="header"]
|=======================
|Language |Library 
|Java     |link:/Software_Projects/Java_Yubico[yubico-java-client]
|PHP      |link:/Software_Projects/Php_Yubico[php-yubico]          
|.NET     |link:/Software_Projects/Php_Yubico[yubico-dotnet-client]   
|Perl     |link:/Software_Projects/Php_Yubico[yubico-perl-client]  
|C        |link:/Software_Projects/Php_Yubico[yubico-c-client]  
|Apex     |link:/Software_Projects/Php_Yubico[yubikey-salesforce-client]    
|=======================


=== Third-party ===

[options="header"]
|=======================
|Language |Library 
|Python   |link:https://github.com/Kami/python-yubico-client[python-yubico-client] 
|Ruby     |link:https://github.com/titanous/yubikey[yubikey]
|Node.js  |link:https://github.com/Kami/node-yubico/blob/master/lib/yubico.js[node-yubico]
|Go       |link:https://npmjs.org/package/yub[Yubigo]
|=======================


pass::[<script src="jquery-1.11.1.min.js"></script><script src="raphael-min.js"></script><script src="underscore-min.js"></script><script src="sequence-diagram-min.js"></script><script>$(".diagram").sequenceDiagram({theme: 'simple'});</script>]

