== What is PIV? ==
abbr:PIV[Personal Identity Verification], or FIPS 201, is a US government standard. It enables RSA or ECC sign/encrypt operations using a private key stored on a smartcard (such as the YubiKey NEO), through common interfaces like PKCS#11.

PIV is primarily used for non-web applications.


=== Advantages
PIV has the following advantages:

 - *Built-in support*. Common operating systems support PIV out of the box
 - *United States government standard*
 - *Flexible*. PIV is a crypto toolbox that can be used to perform all common operations

 
=== Software with PIV support

 - https://support.apple.com/kb/PH13936[OS X]
 ** Client-side authentication to PK-enabled website (HTTPS)
 ** Remote access (VPN)
 ** Port-based Network Access Control
 ** Unlocking keychains
 ** Code signing
 - https://technet.microsoft.com/en-us/library/ff404304(v=ws.10).aspx[Windows]
 ** Login
 ** Remote desktop
 - link:/yubico-piv-tool/SSH_with_PIV_and_PKCS11.html[SSH]
 
 
== Configure the PIV features of a YubiKey
Yubico provides two applications for configuring the PIV features of a YubiKey:

GUI:: link:/yubikey-piv-manager[yubikey-piv-manager]
Command-line:: link:/yubico-piv-tool[yubico-piv-tool]
