== Supported PIV Configuration Tools

As Yubico grows and adds additional features, new software and tools are released to meet the user requirements for using the YubiKey. The YubiKey PIV Application has two supported tools for managing the functionality and data loaded; YubiKey Manager (YKman) and the Yubico CLI PIV Tool (piv-tool). Both tools will function with any YubiKey which supports PIV, but choosing the correct tool for the task at hand will be beneficial to the user’s experience.


=== Yubikey Manager

The https://developers.yubico.com/yubikey-manager-qt/[YubiKey Manager] is a cross-platform application for configuring any YubiKey over all USB interfaces, including the Privilege and Identification Card (PIV). Built on Python, YubiKey Manager was designed to provide a central and standardized platform for initialization of YubiKeys, as well as the loading of cryptographic secrets onto the various supported functions. In addition to a user-friendly GUI, YubiKey Manager has a robust CLI allowing the tool to excel in automating the rapid deployment of YubiKeys.

While YubiKey Manager supports the vast majority of all of the functions supported on PIV, there are some edge cases where commands have not yet been included. Further, as YubiKey Manager is a general purpose tool, it pulls from a number of different libraries, which makes using it as a reference architecture more difficult. YubiKey Manager is actively being developed, with new features included in each release.

=== Yubico PIV Tool

The https://developers.yubico.com/yubico-piv-tool/[Yubico PIV Tool] is used for interacting only with the Privilege and Identification Card (PIV) application on a YubiKey. It contains a C library and a PKCS#11 interface (called YKCS11) as well as a command line interface (CLI). The Yubico PIV Tool is a handy tool for developers and administrators and the YKCS11 module can be used to expose the YubiKey's smart card functionality (or PIV interface) to applications that communicate with hard tokens through the PKCS#11 API; applications like OpenSSL, OpenSSH, JAVA, FireFox and the like.

While the Yubico PIV Tool allows for the CLI to be used as part of a scripted process, the lack of support beyond the PIV functions prevents it from being as script friendly as YubiKey Manager. The lack of a GUI interface also prevents the Yubico PIV tool from being accessable to new users who do not have a prior understanding of PIV and Smart Card concepts. However, as a purpose built interface on just the ykpiv library, the Yubico PIV Tool is an excellent reference architecute for any parties interested in supporting the YubiKey as a PIV smart card natively.


[NOTE]
====
See https://www.yubico.com/products/services-software/download/smart-card-drivers-tools/[Smart card drivers and tools]
for complementary tools and system compatibility.
====
