== Supported PIV Configuration Tools

=== Yubikey Manager

The https://developers.yubico.com/yubikey-manager-qt/[YubiKey Manager] is a cross-platform application for configuring
any YubiKey over all USB interfaces, including the Privilege and Identification Card (PIV). It is a handy and intuitive
tool to configure individual YubiKeys
for every day use.

=== Yubico PIV Tool

The https://developers.yubico.com/yubico-piv-tool/[Yubico PIV Tool] is used for interacting only with the Privilege and
Identification Card (PIV) application on a YubiKey. It contains a C library and a PKCS#11 interface (called YKCS11) as
well as a command line interface (CLI). The Yubico PIV Tool is a handy tool for developers and administrators and
the YKCS11 module can be used to expose the YubiKey's smart card functionality (or PIV interface) to applications that
communicate with hard tokens through the PKCS#11 API; applications like OpenSSL, OpenSSH, JAVA, FireFox... etc.

[NOTE]
====
See https://www.yubico.com/products/services-software/download/smart-card-drivers-tools/[Smart card drivers and tools]
for complementary tools and system compatibility.
====