== Prerequisites and Preparations

The audience of this document is an experienced systems administrator with a good understanding of Microsoft Hyper-V virtualization management. In addition, it is helpful to be familiar with the terminology, software and tools specific to YubiHSM 2. As a primer for these, refer to link:Terminology.adoc[the Terminology chapter in this guide].

In order to follow the steps provided in this guide, be sure to meet the following prerequisites:

* Microsoft Windows Server 2016 or higher. The operating system should be installed in a secure computer network. The system administrator must also have elevated system privileges.

* YubiHSM 2 software and tools for Windows downloaded from the link:https://developers.yubico.com/YubiHSM2/Releases/[Yubico YubiHSM 2 Release page] and available on the system to be used.

* Two (2) YubiHSM 2 devices, one for deployment and one for backup in hardware.

* Your organization's policies may require key custodians to be available for the YubiHSM 2 deployment. For more information about key custodians and the associated ‘M of N’ key shares, see link:../YubiHSM_2_Windows_Deployment_Guide/Prerequisites_and_Preparations.adoc#key-splitting-and-key-custodians["Key Splitting and Key Custodians" in the YubiHSM 2 Windows Deployment Guide].


=== Configuration for this Integration

For the integration described in this guide, the following hardware and software configuration was used:

* Microsoft Windows Server 2016.

* Yubico YubiHSM v 2.1.2.

* Yubico YubiHSM v 2.1.2 software tools.


link:Basic_Setup_of_YubiHSM_2_and_HGS.adoc[Next: Basic Setup of YubiHSM 2 and HGS]
