== YubiHSM 2: Practical Guide

This tutorial will cover:

- Basic YubiHSM 2 setup
- Connecting to YubiHSM 2
- Generating an Authkey on the device
- Generating an Asymmetric Object
- Generate a Wrapkey
- Exporting/Importing an Object under wrap

The purpose of this tutorial is to demonstrate basic functionalities of different key types, Authkey, Asymmetric and Wrapkeys. We start with a fresh YubiHSM 2 configuration and we will proceed in generating a new Authkey.
Then we generate an Asymmetric key for signing purposes. We will sign an arbitrary amount of data and verify that our signature is correct.
Part of this documentation is to demonstrate how to back up a key on a second YubiHSM 2. We will do so by wrapping the Asymmetric key and re-importing it into the same device.

Before reading this document you should get familiar with concepts such as: `Sessions`, `Domains`, `Capabilities` described in the link:../Concepts/index.html[Concepts] Section.

=== Set Up the Environment

- Get the latest binaries from link:../Releases[SDK download]
- Install all libraries
- Make sure your device is accessible by the connector. This is accomplished either by running the connector as a superuser or by using an appropriate link:../Component_Reference/yubihsm-connector[udev_rule].

=== Start Up

To physically reset the YubiHSM 2 insert the device while holding the touch sensor for 10 seconds.

Start the connector

  $ yubihsm-connector -d

Check the status of your connector and device by visiting `http://127.0.0.1:12345/connector/status` with a browser

=== Setting Up YubiHSM 2 Connection

Start yubihsm-shell

  $ yubihsm-shell

Connect to YubiHSM2

  yubihsm> connect

Set keepalive active to facilitate usability during first time use. Remember that this will consume one session

 yubihsm> keepalive 25

Enable debug

 yubihsm> debug all

=== Sessions

By default the YubiHSM 2 comes with a pre-installed Authkey with Object ID `1` and password `password`. Issue the command `session open` followed by the Authkey ID you want to use and the derivation password.

  yubihsm> session open 1 password

To close a session run

  yubihsm> session close 0

List the objects in the device

  yubihsm> list objects 0

=== Adding a new Authkey

Before moving on make sure you are familiar with concepts of link:../Concepts/Capability.html[Capabilities] and link:../Concepts/Domain.html[Domains].

Add an Authkey with ID `2` belonging to all possible *Domains*, with all *Capabilities* enabled and with password `password`.

  yubishm> put authentication 0 2 0xffff 0xffffffff password

For our example we are going to generate an Authkey with selected Capabilities and Domains. Learn more about existing key Types link:../Concepts/Object.html[here].

  yubihsm> put authkey 0 2 yubico 1,2,3 generate_wrapkey,asymmetric_gen,export_wrapped,audit,attest,reset,put_wrapkey,import_wrapped,delete_asymmetric asymmetric_sign_ecdsa,export_under_wrap password

IMPORTANT:  export_wrapped allows to create objects that can perform export_wrap command. +
 export_under_wrap allows to create object that can be exported under wrap.

Note how the command above has two distinct sets of Capabilities. This is because Authekys Object also have link:../Concepts/Capability.html[Delegated Capabilities].

List all object to see the newly created object

 yubishm> list objects 0 2 any 0 0 any

Next, let's start using our newly created Authkey

 yubihsm> session open 2 password

=== Generate a Key for Signing

We now proceed to genrate a new key type, Asymmetric. In our example we will use this key to sign some data and we will also export this key _under wrap_ to another HSM for backup purposes.

  yubihsm> generate asymmetric 2 100 label_ecdsa_sign 1,2,3 export_under_wrap,asymmetric_sign_ecdsa ecp256

If successful you will see this message: "_Generated Asymmetric key 0x0064_".

=== Prepare to sign with the new Authkey

We are going to create a binary digest of the data to be signed, in our example we use OpenSSL.

 $ openssl dgst -sha256 -binary yubihsm-connector > yubihsm-connector.sha

////
don't remember if we had to switch to auth key 1 to sign, key 2 could not
#close session and move back to your main key with all capabilities, default id:1
session open 1 password
////

and sign the data with our newly generated Asymmetric key. In this example we sign the yubihsm-connector binary

  yubihsm> sign ecdsa 0 100 ecdsa-sha256 yubihsm-connector.sha

the output is a signature like the one below:

  MEUCIQDrBqS04LN5YdyWGiD4iaEjfl1dn+W4cl97uMMXDpoaiQIgEBe/G/FgP4cumnO3K2XWToAnPvnuVDOnqHPiuUS0q5g=

We will store the signature in a temporary file so that we'll be able to verify it later

 $ touch sign.sig
 $ echo MEUCIQDrBqS04LN5YdyWGiD4iaEjfl1dn+W4cl97uMMXDpoaiQIgEBe/G/FgP4cumnO3K2XWToAnPvnuVDOnqHPiuUS0q5g= > sign.sig

We extract the public key from our Asymmetric key which we will later use to verify the signature

 yubihsm> get pubkey 0 100 ecdsa_pub.key

Convert signature to binary

  $ base64 -d sign.sig > binary_sign.sig

Verify the signature with OpenSSL

  $ openssl dgst -signature bin_sign.sig -verify ecdsa_pub.key yubihsm-connector.sha
  OK

=== Export Under Wrap

Time to export the key under wrap to a second YubiHSM 2 (in this example, we will export to the same HSM for convenience)

Reconnect to our new key
 yubishm> session open 2

Let's make sure we have the right Capabilities. We check the Capabilities of the Object we want to wrap first

 yubihsm> get objectinfo 0 100 authkey

Now we proceed in adding the Wrapkey.

First we generate our key. For example, we use the YubiHSM 2 to generate 16 random bytes. You want to save this somewhere safe most probably

  yubihsm> get random 0 16
  9207653411df91fd36c12faa6886d5c4

CAUTION: Add a Wrapkey to the device with Capabilities of the target Object. Notice the *Delegated Capabilities* associated with the Object need to be the same as the Object we want to import under wrap.

 yubihsm> put wrapkey 0 200 label_wrapkey 1,2,3 import_wrapped,export_wrapped asymmetric_sign_ecdsa 9207653411df91fd36c12faa6886d5c4

Wrap the Asymmetric key with our Wrapkey with ID `200` and save it to a file

  yubihsm> get wrapped 0 200 asymmetric 100 wrapped_ecdsa.key

Delete the Asymmetric key from the YubiHSM 2. We are going to re-import the key on the same device so we need to first delete the existing object

 yubihsm> delete 1 200 asymmetric

We import the wrapped ECDSA key back into the YubiHSM 2

 yubihsm> put wrapped 1 200 wrapped_ecdsa.key
