= Passkey for developers overview
:description: Passkey concepts essential to help you begin your implementation journey
:keywords: passkey, passkeys, developer, high assurance, FIDO2, CTAP, WebAuthn

Passkey concepts that are essential to help you begin your implementation journey

This page contains links to other reference resources to help further build your understanding of underlying passkey concepts. It’s important to understand these concepts, but if you wish to skip this section, the resources will be linked throughout the rest of this guide

== List of concepts

* link:/Passkeys/Passkey_concepts/Authenticator_types.html[Authenticator types]
* link:/Passkeys/Passkey_concepts/Discoverable_vs_non-discoverable_credentials.html[Discoverable and non-discoverable credentials]
* link:/Passkeys/Passkey_concepts/Single_device_vs_multi_device_credentials.html[Single device vs multi device credentials]
* link:/Passkeys/Passkey_concepts/User_verification.html[User verification]
//* [Hybrid flows](link to guidance)
//* [Security and privacy considerations](link to guidance)

== Implementation guidance
The remainder of this guide will focus on implementation guidance to help assist you in adding passkey support to your application.

The references below will be split into two sections: Relying party implementation guidance, and client application implementation guidance.

=== Relying party implementation guidance
This guide will focus on helping you to create a backend application that supports passkeys. This will include core concepts, code samples, and best practices needed to implement the inputs and outputs needed to facilitate authentication and registration ceremonies. We will also cover implementation differences between low and high assurance scenarios.

link:/Passkeys/Passkey_relying_party_implementation_guidance/[Continue to passkey relying party implementation guidance]

=== Client application implementation guidance
This guide will focus on helping you to create a client application that allows your users to leverage their passkeys. This will include code samples, UI/UX best practices, and user flows that can be used to create a seamless authentication, and credential management experience for your users. 

link:/Passkeys/Passkey_client_application_implementation_guidance/[Continue to passkey client application implementation guidance]

