== FAQ
++++
<div class="last-updated-banner">
    <!-- Simple clock icon -->
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" d="M12 6v6h4.5m4.5 0a9 9 0 11-18 0 9 9 0 0118 0z" />
    </svg>
    <span>Last Updated on 14 November 2025</span>
</div>
++++


=== Question: What value does the Yubico SDK for iOS provide?

*Answer*: The Yubico SDK for iOS provides complete control over every aspect of the WebAuthn registration/authentication flow and offers libraries to interact with YubiKey authentication modules such as Challenge-Response, TOTP/HOTP (via OATH), and PIV.

=== Question: Can I just use WKWebView inside my app for WebAuthn flow?

*Answer*: Apple does not support FIDO2 security keys for the WebAuthn flow using a link:https://developer.apple.com/documentation/webkit/wkwebview[WKWebView] ^1^. You will need to rely on Safari browser, or embed the link:https://developer.apple.com/documentation/safariservices/sfsafariviewcontroller[SFSafariViewController] or link:https://developer.apple.com/documentation/authenticationservices/aswebauthenticationsession[ASWebAuthenticationSession] into a native app.

NOTE: ^1^Apple does technically support passkeys/WebAuthn flow using an embedded WKWebView in iOS/iPadOS 16.1 and later. However, this requires direct authentication to known host that is synced/associated with the native app using link:https://developer.apple.com/documentation/xcode/supporting-associated-domains[Associated Domains]


=== Question: What Apple devices support the NFC for WebAuthn flow via Safari browser?

*Answer*: All iPhones 7 and newer support the NFC protocol for the WebAuthn flow.

[NOTE]
======
The iPhone 6 and iPhone SE have NFC but with limited capabilities used for Apple Pay, thus cannot be used for authentication flows.
======

[NOTE]
======
iPads do not have NFC capabilities.
======
