== YubiCloud Connector Libraries

[Note]
======
<<<<<<< HEAD
Yubico has declared end-of-life of YubiKey Validation Server (YK-VAL) and YubiKey Key Storage Module (YK-KSM). These have been moved to link://github.com/YubicoLabs/yubikey-ksm[YubicoLabs] as a reference architecture. See article, link:/support.yubico.com/hc/en-us/articles/360021227000[YK-VAL, YK-KSM and YubiHSM 1 End-of-Life].
=======
Yubico has declared end-of-life for the YubiKey Validation Server (YK-VAL) and YubiKey Key Storage Module (YK-KSM). These have been moved to link://github.com/YubicoLabs/yubikey-ksm[YubicoLabs] as a reference architecture. See article, link:/support.yubico.com/hc/en-us/articles/360021227000[YK-VAL, YK-KSM and YubiHSM 1 End-of-Life].
>>>>>>> 456647ee9dcca05aafc4d68935558d154423db61
======

These libraries help with connecting to the YubiCloud for Yubico OTP validation from a number of different programming languages. Learn how to use a connector library link:/OTP/Libraries/Using_a_library.html[here].

PHP:: link:/php-yubico/[php-yubico]
C:: link:/yubico-c-client/[yubico-c-client]
Java:: link:/yubico-java-client/[yubico-java-client]
DotNET:: link:/yubico-dotnet-client/[yubico-dotnet-client]
Perl:: link:/yubico-perl-client/[yubico-perl-client]
Windows:: link:/windows-apis[COM API]

Third party implementations can be discovered on link:https://github.com/search?q=yubico+client[GitHub] for example.
