== YubiCloud Connector Libraries

[Note]
======
Yubico has declared end-of-life for the YubiKey Validation Server (YK-VAL) and YubiKey Key Storage Module (YK-KSM). These have been moved to link://github.com/YubicoLabs/yubikey-ksm[YubicoLabs] as a reference architecture. See article, link://support.yubico.com/hc/en-us/articles/360021227000[YK-VAL, YK-KSM and YubiHSM 1 End-of-Life].
======

These libraries are deprecated and no longer maintained. They showed how to connect to the YubiCloud for Yubico OTP validation from a number of different programming languages. Learn how to use a connector library link:/OTP/Libraries/Using_a_library.html[here].

PHP:: link:https://github.com/Yubico/php-yubico/[php-yubico] (deprecated and no longer maintained)
C:: link:https://github.com/Yubico/yubico-c-client/[yubico-c-client] (deprecated and no longer maintained)
Java:: link:https://github.com/Yubico/yubico-java-client/[yubico-java-client] (deprecated and no longer maintained)
DotNET:: link:https://github.com/Yubico/yubico-dotnet-client/[yubico-dotnet-client] (deprecated and no longer maintained)
Perl:: link:https://github.com/Yubico/yubico-perl-client/[yubico-perl-client] (deprecated and no longer maintained)

Third party implementations can be discovered on link:https://github.com/search?q=yubico+client[GitHub] for example.
