== OATH Walk-Through


=== Getting Started: YubiKey with OATH
The YubiKey supports Open Authentication (OATH) standards for generating one-time password (OTP) codes. Configure the YubiKey to generate the OTP for users to enter as their passcode.

The YubiKey-generated passcode can be used as one of the authentication options in two-factor or multi-factor authentication. The user’s login credentials are typically the other half of the two-factor authentication. Go to link:https://twofactorauth.org/[Two Factor Auth (2FA)] for a list of software and web sites that support two-factor authentication.


=== Requirements

* link:https://gradle.org/install/[Install the Gradle build tool]
* link:..//YubiKey_OATH_software.html[Configure the YubiKey using the tools to read and generate the OATH codes]. A developer or administrator configures the YubiKey for one of the supported methods.
•	Provide secret key. Go to the link:https://upgrade.yubico.com/getapikey/[Yubico API key signup page] to generate a shared symmetric key for use with Yubico Web Services. The YubiKey securely stores it to use in combination with a timestamp or authentication counter to generate the OTP code.
•	OTP verification server. Use the link:https://www.yubico.com/products/services-software/yubicloud/[YubiCloud] server with a Yubico API key, or host one of two link:../../Software_Projects/Yubico_OTP/YubiCloud_Validation_Servers/[YubiCloud Validation Servers].
•	link:https://www.yubico.com/products/compare-products-series/[Supported model of YubiKey]


=== Implementation Methods
The configuration steps below apply to both of the authentication methods:
•	Time-based One-Time Password algorithm (TOTP) — Requires an application that can read OATH codes from YubiKeys. Uses a timestamp to calculate the OTP code.
•	HMAC-based One-time Password algorithm (HOTP) — Can be configured using the YubiKey Manager (GUI, CLI). Uses an authentication counter to calculate the OTP code.


=== Configure YubiKey for Android
Use the Yubico Authenticator app to read OATH codes from your YubiKey over NFC or over USB (link:https://developers.yubico.com/yubioath-android/[Android app for OATH]

:Step 1: If using USB, verify USB connection requirements:

    * Device has either a USB on-the-go adapter or USB-C port
    * Device supports USB Host mode
    * Chip Card Interface Device (CCID) mode enabled on the YubiKey

:Step 2:	From Google Play, download the Yubico Authenticator app to your device.
:Step 3:	Add app for Android device to read OATH codes from YubiKey.

          a) Build the APK to install on the Android device. From the device command line, run the gradle command to build the Android Studio app.
          ....
          $ ./gradlew assemble
          ....
          The compiled file is stored in the directory, ``app/build/outputs/apk``.

          b) Manage OATH credentials by command. See link:https://developers.yubico.com/OATH/YKOATH_Protocol.html[YKOATH protocol specification]. The YKOATH protocol includes commands for: Select, Put, Delete, Set Code, Reset, List, Calculate, Validate, Calculate All, Send Remaining.

:Step 4: Add credentials to the YubiKey

         a)	Select the credential method: Scan a QR code or enter Base32-encoded secret. On the YubiKey, tap the + to select the option.

         b)	Tap the YubiKey or connect it to display the codes.


=== Configure YubiKey for Windows, OS X, or Linux with YubiKey Manager (GUI)
The link:https://developers.yubico.com/yubioath-desktop/[Yubico Authenticator for Desktop] enables you to read OATH codes from your YubiKey over USB. Support the newer OATH implementation as well as the older slot-based implementation.

:Step 1: Verify supported version:

         * Windows 7 or later
         * macOS High Sierra 10.13 or later
         * Ubuntu 16.04 LTS or later

:Step 2: For Linux, ensure the ``pcscd`` service is installed and running.

:Step 3:	If using USB, verify USB connection requirements:

          * Device has either a USB on-the-go adapter or USB-C port
          * Device supports USB Host mode
          * Chip Card Interface Device (CCID) mode enabled on the YubiKey

:Step 4:	Download the YubiOATH Desktop.

:Step 5:	Add credentials to the YubiKey:

          a)	Select the credential method: Scan a QR code or enter Base32-encoded secret. On the YubiKey, tap the + to select the option.
          b)	Tap the YubiKey or connect it to display the codes.
