== YubiKey OATH Software
This page lists software that can read TOTP or HOTP codes from YubiKeys.

NOTE: YubiKeys can also emit HOTP codes via USB without any software.

=== Android
_For YubiKey 4, 5 and NEO._

The link:/yubioath-android[Yubico Authenticator] app enables reading OATH codes from your YubiKey over NFC, or over USB (via a USB on-the-go adapter or by directly connecting a YubiKey 4C or 5Ci to a phone with a USB-C port).

=== Windows, OS X and Linux
_For YubiKey 4, 5, NEO, Standard and Edge._

The link:/yubioath-desktop[Yubico Authenticator for Desktop] enables reading OATH codes from your YubiKey over USB. The tools supports the newer OATH implementation (YubiKey NEO and 4) as well as the older slot-based implementation (YubiKey Standard and Edge).

The ykchalresp command line tool (bundled with link:/yubikey-personalization[Yubikey Personalization]) can generate OATH codes using `ykchalresp -t`. The tool supports the older slot-based implementation (YubiKey Standard and Edge).
