== Desktop and Mobile Authentication
=== Desktop App/Platform Authentication
Yubico’s https://github.com/Yubico/libfido2[libfido2] open source project provides a C library and command-line tools to communicate with a FIDO device over USB, and can verify attestation and assertion signatures. Both FIDO U2F (CTAP1) and FIDO2 (CTAP2) protocols are supported on Linux, MacOS, and Windows platforms. To learn how to use the library, see the https://github.com/Yubico/libfido2/tree/master/examples[examples] directory.

https://blogs.windows.com/msedgedev/2018/07/30/introducing-web-authentication-microsoft-edge/#UZcrEz8uWr1dcz0R.97[Microsoft Edge announced Web Authentication support] which enables FIDO2 devices or Windows Hello users to authenticate without any password on any Windows 10 device, using biometrics or a PIN. The https://docs.microsoft.com/en-us/microsoft-edge/dev-guide/windows-integration/web-authentication[Web Authentication and Windows Hello dev guide] will walk through the flow. This guide highlights how you can detect if Windows Hello is available on a PC.  And how you can set the authenticatorAttachment parameter for the best user experience when registering a FIDO2 capable platform, such as Windows 10.

=== Mobile App/Platform Authentication
==== Android
For U2F over NFC on Android, Yubico has a demo application. See the source code to learn

==== iOS
FIDO support via mobile browsers or platform libraries are still under development.
