== Resident Keys
WebAuthn enables high assurance multi-factor authentication with a passwordless login experience. One of the things that enables this is what’s called resident keys.

Resident key means that the private key is stored in persistent memory on the authenticator, instead of encrypted and stored on the relying party server. If the key is stored on the server, then of course the server needs to return that to the authenticator before the authenticator can decrypt and use it. This of course means that the user needs to provide a username, and usually also a password, before the server can do that.

With resident keys there’s no need for that, since the private key is stored on the authenticator. This means that the user doesn’t even need to enter a username to log in. They can just go to the login page, plug in the authenticator, and tap the button, and that’s it, they’re in. This is what we call “first-factor” authentication. If the authenticator also supports PIN or biometric verification, you can get high assurance multi-factor authentication in a single login step with no passwords.
