== Known Issues

This section covers known issues (as of January 2, 2020) when using 13.3+ Safari browser, SFSafariViewController, orASWebAuthenticationSession.

=== 1. User Verification (PIN Support)

It does not matter whether a FIDO2 PIN is set, required, or preferred: in all those cases, the Safari browser dialog does not prompt for a PIN.

[NOTE]
======
If the service from which the user is authenticating is a U2F flow only, then PIN on FIDO2 is a non-issue and the user will successfully authenticate. Learn more in the link:../WebAuthn_Developer_Guide/User_Presence_vs_User_Verification.adoc[User Presence vs User Verification section of our WebAuthn Developer Guide].
======

==== Required, Preferred, and Discouraged Parameters for User Verification
[options="header"]
|=========================================================================
|Feature                       |Required    |Preferred   |Discouraged

|User Verification (FIDO2 PIN) |Not working |Not working |Working
|=========================================================================

“Required”, “Preferred”, and “Discouraged” are optional parameters sent to the client browser by the WebAuthn RP during user registration.


=== 2. Discoverable Credentials (Resident Key)

When the WebAuthn RP specifies the optional parameter `RequireResidentKey=TRUE`, the registration hangs and the user is never prompted to insert or tap the YubiKey. Learn more in the link:../WebAuthn_Developer_Guide/Resident_Keys.adoc[Discoverable Credentials section of our WebAuthn Developer Guide].

==== Required (TRUE)/Required(FALSE) Parameters for Discoverable Credentials (ResidentKey)
[options="header"]
|=====================================================================================
|Feature                            |Required (TRUE) |Required (FALSE)

|Discoverable Credentials (ResidentKey) |Not working     |Working
|=====================================================================================

`Required: TRUE|FALSE` is an optional parameter sent by the WebAuthn RP to the client.


=== 3. Attestation

If the WebAuthn RP requests any attestation parameter other than `none`, registration fails and the user is never prompted to insert or tap a YubiKey. Learn more in the link:../WebAuthn_Developer_Guide/Attestation.adoc[Attestation section of our WebAuthn Developer Guide].

==== None, Indirect, and Direct Parameters for Attestation
[options="header"]
|=========================================================
|Feature                       |None     |Indirect          |Direct

|Attestation                   |Working  |Not working       |Not working
|=========================================================


link:FAQ.adoc[Next: FAQ]
