== Known Issues (when using Safari)

(Updated Dec 20, 2019) This known issues section will be updated as issues are reported.

=== 1. User Verification (PIN Support)

Whether a FIDO2 PIN is set, required, or preferred, the Safari browser dialog does not prompt for a PIN.

[NOTE]
======
If the service from which the user is authenticating is a U2F flow only, then PIN on FIDO2 is a non-issue and the user will successfully authenticate. Learn more in the link:../WebAuthn_Developer_Guide/User_Presence_vs_User_Verification.adoc[User Presence vs User Verification section of our WebAuthn Developer Guide].
======

==== Required, Preferred, and Discouraged Parameters for User Verification
[options="header"]
|=========================================================================
|Feature                       |Required |Preferred |Discouraged

|User Verification (FIDO2 PIN) |No       |No        |Yes
|=========================================================================

“`Required`”, “`Preferred`”, and “`Discouraged`” are optional parameters sent to the client browser by the WebAuthn RP during user registration.


=== 2. Resident Credentials (Resident Key)

When the WebAuthn RP specifies the optional parameter `RequireResidentKey=TRUE`, the registration hangs and the user is never prompted to insert or tap the YubiKey. Learn more in the link:../WebAuthn_Developer_Guide/Resident_Keys.adoc[Resident Keys section of our WebAuthn Developer Guide].

==== Required (TRUE)/Required(FALSE) Parameters for Resident Credentials (ResidentKey)
[options="header"]
|=====================================================================================
|Feature                            |Required (TRUE) |Required (FALSE)

|Resident Credentials (ResidentKey) |No              |Yes
|=====================================================================================

`Required: TRUE|FALSE` is an optional parameter sent by the WebAuthn RP to the client.


=== 3. Attestation

If the WebAuthn RP requests any attestation parameter other than `none`, registration fails and the user is never prompted to insert or tap a YubiKey. Learn more in the link:../WebAuthn_Developer_Guide/Attestation.adoc[Attestation section of our WebAuthn Developer Guide].

==== None, Indirect, and Direct Parameters for Attestation
[options="header"]
|=========================================================
|Feature                       |None |Indirect |Direct

|Attestation                   |Yes  |No       |No
|=========================================================


link:FAQ.adoc[Next: FAQ]
