== Implementing YubiKey OTP using a library ==
NOTE: YubiKey OTPs can be validated by YubiCloud or a self-hosted validation server.
Throughout this document we will refer to both these alternatives simply as 'YubiCloud'.

This sequence diagram describes a typical YubiKey OTP implementation:

++++
<div class="diagram">
Browser->Server: OTP (and username\n& password)
Note over Server: verify username\nand password
Server->YubiCloud: OTP
YubiCloud-->Server: response
</div>
++++

By using a library, you abstract away the communication with the YubiCloud:

++++
<div class="diagram">
Browser->Server: OTP (and username\n& password)
Note over Server: verify username\nand password
Note over Server: ask library to\nvalidate OTP
</div>
++++

=== Validating OTPs ===
For example, the _ask library to validate OTP_ step in the diagram above could be implemented like this:

[source, python]
----
# otp is the OTP from the Yubikey
otp_is_valid = client.verify(otp)
----

After validating the OTP, you also want to make sure that the YubiKey belongs to the user logging in.
This is done by comparing the first 12 characters of the OTP (which is the YubiKey's ID) with the
YubiKey ID that is associated with the user:

[source, python]
yubikey_belongs_to_user = otp[:12] == user.yubikey_id

=== Provisioning YubiKeys ===
Provisioning is simply a matter of associating the first 12 characters of an OTP with a user in your user database.
This means that you can allow users to self-provision YubiKeys if you want to.

[source, python]
user.yubikey_id = otp[:12] 

=== Client-side ===
The client-side (browser-side) is not handled by libraries. Luckily, you just have to add another text field to your existing login form. From a user point of view, _press Enter_ is replaced with _touch the YubiKey button_.

== Available libraries ==
Have a look at the link:List_of_libraries.html[List of libraries].

== Getting help ==
Feel free to create a topic in http://forum.yubico.com/viewforum.php?f=3[our forum] or an issue in respective library's https://github.com/yubico[GitHub project].


pass::[<script src="jquery-1.11.1.min.js"></script><script src="raphael-min.js"></script><script src="underscore-min.js"></script><script src="sequence-diagram-min.js"></script><script>$(".diagram").sequenceDiagram({theme: 'simple'});</script>]

