== What is YubiHSM 2?

The YubiHSM 2 is a Hardware Security Module that is within reach of all organizations. It provides advanced cryptography, including hashing, asymmetric and symmetric key cryptography, to protect the cryptographic keys that secure critical applications, identities, and sensitive data in an enterprise for certificate authorities, databases, code signing and more.

The YubiHSM 2 has been certified at https://csrc.nist.gov/projects/cryptographic-module-validation-program/certificate/3916[FIPS 140-2 Level 3].

== Documentation overview

The purpose of this documentation is both to provide detailed descriptions of YubiHSM 2 concepts and to work as a reference for commands and APIs provided. Before setting up YubiHSM 2 for the first time, familiarize yourself with the basic concepts and terminology used in the product documentation contained within these pages as well as in the software itself.

- link:Releases[*Releases*] provides access to release notes, downloads, and known issues and limitations.
- link:Product_Overview/[*Product Overview*] gives a high-level description of the YubiHSM 2 offering; product specifications, contents of the SDK, and how to get help.
- link:Concepts[*Concepts*] explains the foundational concepts used; understanding of these concepts is necessary in order to use YubiHSM 2.
- link:Commands/[*Commands*] provides an inventory of all available commands, with yubihsm-shell usage examples.
- link:Component_Reference/[*Component Reference*] is a collection of reference materials for the components included in the SDK: the core libraries, the PKCS#11 module, the Shell, the Key Storage Provider, and more.
- link:Usage_Guides/[*Usage Guides*] contains a number of guides and examples for using YubiHSM 2.
- link:Backup_and_Restore[*Backup and Restore*] informs about how to back up keys, and how to restore from backups.

NOTE: YubiHSM 2 SDK documentation and usage guides are enhanced continuously. Please check back regularly to see what’s new.

== System requirements

The YubiHSM 2 SDK is built and provided for the following operating systems.

[cols="1,1,1", options="header"]
|===
|Operating System | Version | Architecture
|CentOS | 7 | amd64
|Debian | 10 Buster | amd64
|Debian | 11 Bullseye | amd64
|Debian | 12 Bookworm | amd64
|Fedora | 37 | amd64
|Fedora | 38 | amd64
|Ubuntu | 14.04 Trusty Tahr | amd64
|Ubuntu | 16.04 Xenial Xerus | amd64
|Ubuntu | 18.04 Bionic Beaver | amd64
|Ubuntu | 20.04 Focal Fossa | amd64
|Ubuntu | 21.10 Impish Indri | amd64
|Ubuntu | 22.04 Jammy Jellyfish | amd64
|Ubuntu | 23.04 Lunar Lobster | amd64
|Windows | Server 2019 | x64, x86
|Windows | Server 2022 | x64, x86
|macOS | 11 Big Sur, 12 Monterey | amd64, arm64, universal
|===

== License

The YubiHSM 2 SDK is intended for use in development and production environments in conjunction with YubiHSM 2, pursuant to https://www.yubico.com/support/terms-conditions/yubico-toolset-software-license-agreement/[Yubico Toolset Software License Agreement]. By downloading and installing the SDK you agree to the terms of this license.

The released SDK source code is licensed under the https://www.apache.org/licenses/LICENSE-2.0[Apache 2.0] license.

Third party software included in the YubiHSM 2 SDK, and their respective licenses, are listed in the licenses directory inside the SDK package.
