== About the Yubico Developer Program ==
The Yubico developer program provides the tools you need to develop, integrate, and launch your Works with YubiKey product.

== Developer Workflow ==
1. link:#learn[Learn] about YubiKey products and software
   * Read about the open standards and protocols
   * Explore the open source libraries and APIs
   * Check out example projects, guides, and how-to’s
2. link:#connect[Connect] with the the Yubico developer community
    * Ask technical questions
    * Report bugs and request features
    * Explore Yubico’s knowledge base
3. link:#integrate[Integrate] with Yubico
    * Integrate open standards into your product or service
    * Submit a request for a technical integration review
    * Once approved, share your content and imagery with Yubico and get added to the Works with YubiKey catalog

[[learn]]
== Developer Guides ==
The Yubico Developer Program provides workshops, documentation, implementation guides, APIs and SDKs to aid in rapid integration of Yubico technologies including YubiKey integration using any of the supported protocols: FIDO U2F, FIDO2, One-time password (OTP), PIV (smart card), and OpenPGP. These resources can all be found on the developer site.

=== FIDO/WebAuthn ===
The FIDO/WebAuthn open authentication specifications enable strong first-factor, second-factor, and multi-factor authentication options.

* link:/FIDO2/[FIDO2 overview]
* link:/FIDO2/Libraries/Using_a_library.html[Using a FIDO2 library]

=== One-Time Password (OTP)
Yubico OTP is a simple yet strong authentication mechanism that is supported by all YubiKeys. Yubico OTP can be used as the second factor in a 2-factor authentication model or on its own, providing first-factor authentication.

* link:/OTP/[Yubico OTP overview]
* link:/OTP/Guides/Self-hosted_OTP_validation.html[Setup a self-hosted Yubico OTP validation server]
* link:/OTP/Libraries/Using_a_library.html[Using a Yubico OTP library]

=== Personal Identity Verification (PIV)
The YubiKey provides smart card features based on the Personal Identity and Verification Card (PIV) standard over the CCID protocol, which supports smart cards on a USB interface. This enables you to perform RSA or ECC sign and decrypt operations using a private key stored on the YubiKey. 

* link:/PIV/[PIV overview]
* link:/PIV/Guides/Device_setup.html[Device Setup]
* link:/PIV/Guides/SSH_with_PIV_and_PKCS11.html[SSH with PIV and PKCS11]

=== OpenPGP
OpenPGP is a standards-based public key cryptography for signing, encrypting, and decrypting texts, e-mails, files, SSH, etc. Both the YubiKey 4 series and Yubikey NEO can securely hold a PGP key.

* link:/PGP/[PGP overview]
* link:/PGP/Card_edit.html[Card edit]
* link:/PGP/SSH_authentication/[SSH authentication]

=== YubiHSM2
The YubiHSM2 provides advanced cryptography, including hashing, asymmetric and symmetric key cryptography, to protect the cryptographic keys that secure critical applications, identities, and sensitive data in an enterprise for certificate authorities, databases, code signing and more.

* link:/YubiHSM2/Usage_Guides/YubiHSM_quick_start_tutorial.html[YubiHSM quick start tutorial]
* link:/YubiHSM2/Usage_Guides/Admin_guide.html[Admin guide]
* link:/YubiHSM2/Backup_and_Restore/[Backup and restore]

[[connect]]
== Community
There are several communities where you can engage with Yubico developers and enthusiasts.  

[[askTechnicalQuestions]]
=== Ask Technical Questions
For technical questions, try Stack Exchange sites. Stack Exchange is a network of question and answer sites for developers to learn and share their knowledge, which includes link:https://stackoverflow.com/[Stack Overflow].

If you’ve never used a Stack Exchange site then you should review their link:https://stackoverflow.com/help/how-to-ask[guide for asking good questions]. Use the link:https://stackoverflow.com/questions/tagged/yubico[Yubico] tag when link:https://stackoverflow.com/questions/ask/advice?tags=yubico[asking a question].

=== Report bugs and request features
Yubico offers many libraries and tools to help you integrate with YubiKeys and YubiHSMs. Many of these are hosted on GitHub. 

If you’ve never used Github before then you should review link:https://guides.github.com/[Github Guides], particularly the link:https://guides.github.com/features/issues/[Mastering Issues] guide which helps explain how to use Github Issues to report bugs or request features.

=== Explore the knowledge base
link:https://support.yubico.com/support/home[Yubico’s knowledge base] contains guides, troubleshooting tips, and details about all of Yubico’s products. It can help you get started if you are new to YubiKeys.

[[integrate]]
== Integrate
link:https://www.yubico.com/solutions/for-technology-partners/[Join the Works with YubiKey program]. If your service works with YubiKey then submit your integration for a technical review. Once approved, learn how to get your service listed in the link:https://www.yubico.com/solutions/#all[Works with YubiKey catalog].