== What is PGP? ==
abbr:OpenPGP[Pretty Good Privacy] is an open standard for signing and encrypting. It enables RSA or ECC sign/encrypt operations using a private key stored on a smartcard (such as the YubiKey NEO), through common interfaces like PKCS#11.

PGP is not used for web authentication.


=== Advantages
PGP has the following advantages:

 - *De facto standard* in the Gnu/Linux world and for e-mail encryption.
 - *Flexible*. PGP is a crypto toolbox that can be used to perform all common operations.

 
=== Software with OpenPGP Card support

 - GnuPG
 - https://www.opensc-project.org/opensc/wiki/QuickStart#TestingusingOpenSSL[SSH]
 - PAM
 - http://www.scute.org[Firefox/Iceweasel]
 - Thunderbird/Icedove
 - Android (using NFC)
 ** http://www.openkeychain.org/[OpenKeychain]
 ** K-9 Mail
 ** Conversations
 ** Password Store
 ** PGPAuth
 - http://www.symantec.com/products-solutions/families/?fid=encryption[More...]
 
 
== Configure the PGP features of a YubiKey
The YubiKey NEO can be configured and used with any application with support for OpenPGP Card.
