== What is PGP? ==
abbr:OpenPGP[Pretty Good Privacy] is an open standard for signing and encrypting. It enables RSA or ECC sign/encrypt operations using a private key stored on a smartcard (such as the YubiKey NEO), through common interfaces like PKCS#11.

NOTE: PGP is not used for web authentication.


=== Advantages
PGP has the following advantages:

 - *De facto standard* in the Gnu/Linux world and for e-mail encryption.
 - *Flexible*. PGP is a crypto toolbox that can be used to perform all common operations.

 
== Software with OpenPGP Card support

 - https://www.gnupg.org[GnuPG]
 - link:SSH_authentication.html[SSH]
 - http://en.wikipedia.org/wiki/Linux_PAM[PAM]
 - http://www.scute.org[Firefox/Iceweasel]
 - Thunderbird/Icedove
 - Android (using NFC)
 ** http://www.openkeychain.org/[OpenKeychain]
 ** K-9 Mail
 ** Conversations
 ** Password Store
 ** PGPAuth
 - http://www.symantec.com/products-solutions/families/?fid=encryption[More...]
 
 
== Configure the PGP features of a YubiKey
The YubiKey NEO can be configured and used with any application with support for OpenPGP Card:

 - link:Importing_keys.html[Importing keys]
 - link:Card_edit.html[Card edit]
 - link:SSH_authentication.html[SSH authentication]
 
 
== YubiKey firmware
The OpenPGP support in the YubiKey NEO is provided by the open source link:/ykneo-openpgp[ykneo-openpgp] applet.
