== What is PGP? ==
[IMPORTANT]
====
Yubico has learned of a security issue with the OpenPGP Card applet project that is used in the YubiKey NEO. This vulnerability applies to you only if you are using OpenPGP, and you have the OpenPGP applet version 1.0.9 or earlier.
link:https://developers.yubico.com/ykneo-openpgp/SecurityAdvisory%202015-04-14.html[SecurityAdvisory 2015-04-14]
====

abbr:OpenPGP[Pretty Good Privacy] is an open standard for signing and encrypting. It enables RSA or ECC sign/encrypt operations using a private key stored on a smartcard (such as the YubiKey NEO), through common interfaces like PKCS#11.

NOTE: PGP is not used for web authentication.


=== Advantages
PGP has the following advantages:

 - *De facto standard* in the Gnu/Linux world and for e-mail encryption.
 - *Flexible*. PGP is a crypto toolbox that can be used to perform all common operations.

 
== Software with OpenPGP Card support

 - https://www.gnupg.org[GnuPG]
 - link:SSH_authentication[SSH]
 - http://en.wikipedia.org/wiki/Linux_PAM[PAM]
 - http://www.scute.org[Firefox/Iceweasel]
 - Thunderbird/Icedove
 - https://trmm.net/Yubikey[Apple Mail / GPGTools]
 - Android (using NFC)
 ** http://www.openkeychain.org/[OpenKeychain]
 ** K-9 Mail
 ** Conversations
 ** Password Store
 ** PGPAuth
 - http://www.symantec.com/products-solutions/families/?fid=encryption[More...]
 
 
== Configure the PGP features of a YubiKey
The YubiKey NEO can be configured and used with any application with support for OpenPGP Card:

 - link:Importing_keys.html[Importing keys]
 - link:Card_edit.html[Card edit]
 - link:SSH_authentication[SSH authentication]
 - link:Git_signing.html[Git signing]
 
 
== YubiKey firmware
The OpenPGP support in the YubiKey NEO is provided by the open source link:/ykneo-openpgp[ykneo-openpgp] applet.
